/**
 * HarfBuzz-0.0
 */

/// <reference types="node" />
/// <reference path="freetype2-2.0.d.ts" />
/// <reference path="GObject-2.0.d.ts" />
/// <reference path="GLib-2.0.d.ts" />

declare namespace HarfBuzz {

export enum buffer_cluster_level_t {
    MONOTONE_GRAPHEMES,
    MONOTONE_CHARACTERS,
    CHARACTERS,
    GRAPHEMES,
    DEFAULT,
}
export enum buffer_content_type_t {
    INVALID,
    UNICODE,
    GLYPHS,
}
export enum direction_t {
    INVALID,
    LTR,
    RTL,
    TTB,
    BTT,
}
export enum memory_mode_t {
    DUPLICATE,
    READONLY,
    WRITABLE,
    READONLY_MAY_MAKE_WRITABLE,
}
export enum ot_layout_glyph_class_t {
    UNCLASSIFIED,
    BASE_GLYPH,
    LIGATURE,
    MARK,
    COMPONENT,
}
export enum ot_math_constant_t {
    SCRIPT_PERCENT_SCALE_DOWN,
    SCRIPT_SCRIPT_PERCENT_SCALE_DOWN,
    DELIMITED_SUB_FORMULA_MIN_HEIGHT,
    DISPLAY_OPERATOR_MIN_HEIGHT,
    MATH_LEADING,
    AXIS_HEIGHT,
    ACCENT_BASE_HEIGHT,
    FLATTENED_ACCENT_BASE_HEIGHT,
    SUBSCRIPT_SHIFT_DOWN,
    SUBSCRIPT_TOP_MAX,
    SUBSCRIPT_BASELINE_DROP_MIN,
    SUPERSCRIPT_SHIFT_UP,
    SUPERSCRIPT_SHIFT_UP_CRAMPED,
    SUPERSCRIPT_BOTTOM_MIN,
    SUPERSCRIPT_BASELINE_DROP_MAX,
    SUB_SUPERSCRIPT_GAP_MIN,
    SUPERSCRIPT_BOTTOM_MAX_WITH_SUBSCRIPT,
    SPACE_AFTER_SCRIPT,
    UPPER_LIMIT_GAP_MIN,
    UPPER_LIMIT_BASELINE_RISE_MIN,
    LOWER_LIMIT_GAP_MIN,
    LOWER_LIMIT_BASELINE_DROP_MIN,
    STACK_TOP_SHIFT_UP,
    STACK_TOP_DISPLAY_STYLE_SHIFT_UP,
    STACK_BOTTOM_SHIFT_DOWN,
    STACK_BOTTOM_DISPLAY_STYLE_SHIFT_DOWN,
    STACK_GAP_MIN,
    STACK_DISPLAY_STYLE_GAP_MIN,
    STRETCH_STACK_TOP_SHIFT_UP,
    STRETCH_STACK_BOTTOM_SHIFT_DOWN,
    STRETCH_STACK_GAP_ABOVE_MIN,
    STRETCH_STACK_GAP_BELOW_MIN,
    FRACTION_NUMERATOR_SHIFT_UP,
    FRACTION_NUMERATOR_DISPLAY_STYLE_SHIFT_UP,
    FRACTION_DENOMINATOR_SHIFT_DOWN,
    FRACTION_DENOMINATOR_DISPLAY_STYLE_SHIFT_DOWN,
    FRACTION_NUMERATOR_GAP_MIN,
    FRACTION_NUM_DISPLAY_STYLE_GAP_MIN,
    FRACTION_RULE_THICKNESS,
    FRACTION_DENOMINATOR_GAP_MIN,
    FRACTION_DENOM_DISPLAY_STYLE_GAP_MIN,
    SKEWED_FRACTION_HORIZONTAL_GAP,
    SKEWED_FRACTION_VERTICAL_GAP,
    OVERBAR_VERTICAL_GAP,
    OVERBAR_RULE_THICKNESS,
    OVERBAR_EXTRA_ASCENDER,
    UNDERBAR_VERTICAL_GAP,
    UNDERBAR_RULE_THICKNESS,
    UNDERBAR_EXTRA_DESCENDER,
    RADICAL_VERTICAL_GAP,
    RADICAL_DISPLAY_STYLE_VERTICAL_GAP,
    RADICAL_RULE_THICKNESS,
    RADICAL_EXTRA_ASCENDER,
    RADICAL_KERN_BEFORE_DEGREE,
    RADICAL_KERN_AFTER_DEGREE,
    RADICAL_DEGREE_BOTTOM_RAISE_PERCENT,
}
export enum ot_math_kern_t {
    TOP_RIGHT,
    TOP_LEFT,
    BOTTOM_RIGHT,
    BOTTOM_LEFT,
}
export enum ot_name_id_predefined_t {
    COPYRIGHT,
    FONT_FAMILY,
    FONT_SUBFAMILY,
    UNIQUE_ID,
    FULL_NAME,
    VERSION_STRING,
    POSTSCRIPT_NAME,
    TRADEMARK,
    MANUFACTURER,
    DESIGNER,
    DESCRIPTION,
    VENDOR_URL,
    DESIGNER_URL,
    LICENSE,
    LICENSE_URL,
    TYPOGRAPHIC_FAMILY,
    TYPOGRAPHIC_SUBFAMILY,
    MAC_FULL_NAME,
    SAMPLE_TEXT,
    CID_FINDFONT_NAME,
    WWS_FAMILY,
    WWS_SUBFAMILY,
    LIGHT_BACKGROUND,
    DARK_BACKGROUND,
    VARIATIONS_PS_PREFIX,
    INVALID,
}
export enum paint_composite_mode_t {
    CLEAR,
    SRC,
    DEST,
    SRC_OVER,
    DEST_OVER,
    SRC_IN,
    DEST_IN,
    SRC_OUT,
    DEST_OUT,
    SRC_ATOP,
    DEST_ATOP,
    XOR,
    PLUS,
    SCREEN,
    OVERLAY,
    DARKEN,
    LIGHTEN,
    COLOR_DODGE,
    COLOR_BURN,
    HARD_LIGHT,
    SOFT_LIGHT,
    DIFFERENCE,
    EXCLUSION,
    MULTIPLY,
    HSL_HUE,
    HSL_SATURATION,
    HSL_COLOR,
    HSL_LUMINOSITY,
}
export enum paint_extend_t {
    PAD,
    REPEAT,
    REFLECT,
}
export enum unicode_combining_class_t {
    NOT_REORDERED,
    OVERLAY,
    NUKTA,
    KANA_VOICING,
    VIRAMA,
    CCC10,
    CCC11,
    CCC12,
    CCC13,
    CCC14,
    CCC15,
    CCC16,
    CCC17,
    CCC18,
    CCC19,
    CCC20,
    CCC21,
    CCC22,
    CCC23,
    CCC24,
    CCC25,
    CCC26,
    CCC27,
    CCC28,
    CCC29,
    CCC30,
    CCC31,
    CCC32,
    CCC33,
    CCC34,
    CCC35,
    CCC36,
    CCC84,
    CCC91,
    CCC103,
    CCC107,
    CCC118,
    CCC122,
    CCC129,
    CCC130,
    CCC132,
    ATTACHED_BELOW_LEFT,
    ATTACHED_BELOW,
    ATTACHED_ABOVE,
    ATTACHED_ABOVE_RIGHT,
    BELOW_LEFT,
    BELOW,
    BELOW_RIGHT,
    LEFT,
    RIGHT,
    ABOVE_LEFT,
    ABOVE,
    ABOVE_RIGHT,
    DOUBLE_BELOW,
    DOUBLE_ABOVE,
    IOTA_SUBSCRIPT,
    INVALID,
}
export enum unicode_general_category_t {
    CONTROL,
    FORMAT,
    UNASSIGNED,
    PRIVATE_USE,
    SURROGATE,
    LOWERCASE_LETTER,
    MODIFIER_LETTER,
    OTHER_LETTER,
    TITLECASE_LETTER,
    UPPERCASE_LETTER,
    SPACING_MARK,
    ENCLOSING_MARK,
    NON_SPACING_MARK,
    DECIMAL_NUMBER,
    LETTER_NUMBER,
    OTHER_NUMBER,
    CONNECT_PUNCTUATION,
    DASH_PUNCTUATION,
    CLOSE_PUNCTUATION,
    FINAL_PUNCTUATION,
    INITIAL_PUNCTUATION,
    OTHER_PUNCTUATION,
    OPEN_PUNCTUATION,
    CURRENCY_SYMBOL,
    MODIFIER_SYMBOL,
    MATH_SYMBOL,
    OTHER_SYMBOL,
    LINE_SEPARATOR,
    PARAGRAPH_SEPARATOR,
    SPACE_SEPARATOR,
}
export enum aat_layout_feature_selector_t {
    B_AAT_LAYOUT_FEATURE_SELECTOR_INVALID,
    B_AAT_LAYOUT_FEATURE_SELECTOR_ALL_TYPE_FEATURES_ON,
    B_AAT_LAYOUT_FEATURE_SELECTOR_ALL_TYPE_FEATURES_OFF,
    B_AAT_LAYOUT_FEATURE_SELECTOR_REQUIRED_LIGATURES_ON,
    B_AAT_LAYOUT_FEATURE_SELECTOR_REQUIRED_LIGATURES_OFF,
    B_AAT_LAYOUT_FEATURE_SELECTOR_COMMON_LIGATURES_ON,
    B_AAT_LAYOUT_FEATURE_SELECTOR_COMMON_LIGATURES_OFF,
    B_AAT_LAYOUT_FEATURE_SELECTOR_RARE_LIGATURES_ON,
    B_AAT_LAYOUT_FEATURE_SELECTOR_RARE_LIGATURES_OFF,
    B_AAT_LAYOUT_FEATURE_SELECTOR_LOGOS_ON,
    B_AAT_LAYOUT_FEATURE_SELECTOR_LOGOS_OFF,
    B_AAT_LAYOUT_FEATURE_SELECTOR_REBUS_PICTURES_ON,
    B_AAT_LAYOUT_FEATURE_SELECTOR_REBUS_PICTURES_OFF,
    B_AAT_LAYOUT_FEATURE_SELECTOR_DIPHTHONG_LIGATURES_ON,
    B_AAT_LAYOUT_FEATURE_SELECTOR_DIPHTHONG_LIGATURES_OFF,
    B_AAT_LAYOUT_FEATURE_SELECTOR_SQUARED_LIGATURES_ON,
    B_AAT_LAYOUT_FEATURE_SELECTOR_SQUARED_LIGATURES_OFF,
    B_AAT_LAYOUT_FEATURE_SELECTOR_ABBREV_SQUARED_LIGATURES_ON,
    B_AAT_LAYOUT_FEATURE_SELECTOR_ABBREV_SQUARED_LIGATURES_OFF,
    B_AAT_LAYOUT_FEATURE_SELECTOR_SYMBOL_LIGATURES_ON,
    B_AAT_LAYOUT_FEATURE_SELECTOR_SYMBOL_LIGATURES_OFF,
    B_AAT_LAYOUT_FEATURE_SELECTOR_CONTEXTUAL_LIGATURES_ON,
    B_AAT_LAYOUT_FEATURE_SELECTOR_CONTEXTUAL_LIGATURES_OFF,
    B_AAT_LAYOUT_FEATURE_SELECTOR_HISTORICAL_LIGATURES_ON,
    B_AAT_LAYOUT_FEATURE_SELECTOR_HISTORICAL_LIGATURES_OFF,
    B_AAT_LAYOUT_FEATURE_SELECTOR_UNCONNECTED,
    B_AAT_LAYOUT_FEATURE_SELECTOR_PARTIALLY_CONNECTED,
    B_AAT_LAYOUT_FEATURE_SELECTOR_CURSIVE,
    B_AAT_LAYOUT_FEATURE_SELECTOR_UPPER_AND_LOWER_CASE,
    B_AAT_LAYOUT_FEATURE_SELECTOR_ALL_CAPS,
    B_AAT_LAYOUT_FEATURE_SELECTOR_ALL_LOWER_CASE,
    B_AAT_LAYOUT_FEATURE_SELECTOR_SMALL_CAPS,
    B_AAT_LAYOUT_FEATURE_SELECTOR_INITIAL_CAPS,
    B_AAT_LAYOUT_FEATURE_SELECTOR_INITIAL_CAPS_AND_SMALL_CAPS,
    B_AAT_LAYOUT_FEATURE_SELECTOR_SUBSTITUTE_VERTICAL_FORMS_ON,
    B_AAT_LAYOUT_FEATURE_SELECTOR_SUBSTITUTE_VERTICAL_FORMS_OFF,
    B_AAT_LAYOUT_FEATURE_SELECTOR_LINGUISTIC_REARRANGEMENT_ON,
    B_AAT_LAYOUT_FEATURE_SELECTOR_LINGUISTIC_REARRANGEMENT_OFF,
    B_AAT_LAYOUT_FEATURE_SELECTOR_MONOSPACED_NUMBERS,
    B_AAT_LAYOUT_FEATURE_SELECTOR_PROPORTIONAL_NUMBERS,
    B_AAT_LAYOUT_FEATURE_SELECTOR_THIRD_WIDTH_NUMBERS,
    B_AAT_LAYOUT_FEATURE_SELECTOR_QUARTER_WIDTH_NUMBERS,
    B_AAT_LAYOUT_FEATURE_SELECTOR_WORD_INITIAL_SWASHES_ON,
    B_AAT_LAYOUT_FEATURE_SELECTOR_WORD_INITIAL_SWASHES_OFF,
    B_AAT_LAYOUT_FEATURE_SELECTOR_WORD_FINAL_SWASHES_ON,
    B_AAT_LAYOUT_FEATURE_SELECTOR_WORD_FINAL_SWASHES_OFF,
    B_AAT_LAYOUT_FEATURE_SELECTOR_LINE_INITIAL_SWASHES_ON,
    B_AAT_LAYOUT_FEATURE_SELECTOR_LINE_INITIAL_SWASHES_OFF,
    B_AAT_LAYOUT_FEATURE_SELECTOR_LINE_FINAL_SWASHES_ON,
    B_AAT_LAYOUT_FEATURE_SELECTOR_LINE_FINAL_SWASHES_OFF,
    B_AAT_LAYOUT_FEATURE_SELECTOR_NON_FINAL_SWASHES_ON,
    B_AAT_LAYOUT_FEATURE_SELECTOR_NON_FINAL_SWASHES_OFF,
    B_AAT_LAYOUT_FEATURE_SELECTOR_SHOW_DIACRITICS,
    B_AAT_LAYOUT_FEATURE_SELECTOR_HIDE_DIACRITICS,
    B_AAT_LAYOUT_FEATURE_SELECTOR_DECOMPOSE_DIACRITICS,
    B_AAT_LAYOUT_FEATURE_SELECTOR_NORMAL_POSITION,
    B_AAT_LAYOUT_FEATURE_SELECTOR_SUPERIORS,
    B_AAT_LAYOUT_FEATURE_SELECTOR_INFERIORS,
    B_AAT_LAYOUT_FEATURE_SELECTOR_ORDINALS,
    B_AAT_LAYOUT_FEATURE_SELECTOR_SCIENTIFIC_INFERIORS,
    B_AAT_LAYOUT_FEATURE_SELECTOR_NO_FRACTIONS,
    B_AAT_LAYOUT_FEATURE_SELECTOR_VERTICAL_FRACTIONS,
    B_AAT_LAYOUT_FEATURE_SELECTOR_DIAGONAL_FRACTIONS,
    B_AAT_LAYOUT_FEATURE_SELECTOR_PREVENT_OVERLAP_ON,
    B_AAT_LAYOUT_FEATURE_SELECTOR_PREVENT_OVERLAP_OFF,
    B_AAT_LAYOUT_FEATURE_SELECTOR_HYPHENS_TO_EM_DASH_ON,
    B_AAT_LAYOUT_FEATURE_SELECTOR_HYPHENS_TO_EM_DASH_OFF,
    B_AAT_LAYOUT_FEATURE_SELECTOR_HYPHEN_TO_EN_DASH_ON,
    B_AAT_LAYOUT_FEATURE_SELECTOR_HYPHEN_TO_EN_DASH_OFF,
    B_AAT_LAYOUT_FEATURE_SELECTOR_SLASHED_ZERO_ON,
    B_AAT_LAYOUT_FEATURE_SELECTOR_SLASHED_ZERO_OFF,
    B_AAT_LAYOUT_FEATURE_SELECTOR_FORM_INTERROBANG_ON,
    B_AAT_LAYOUT_FEATURE_SELECTOR_FORM_INTERROBANG_OFF,
    B_AAT_LAYOUT_FEATURE_SELECTOR_SMART_QUOTES_ON,
    B_AAT_LAYOUT_FEATURE_SELECTOR_SMART_QUOTES_OFF,
    B_AAT_LAYOUT_FEATURE_SELECTOR_PERIODS_TO_ELLIPSIS_ON,
    B_AAT_LAYOUT_FEATURE_SELECTOR_PERIODS_TO_ELLIPSIS_OFF,
    B_AAT_LAYOUT_FEATURE_SELECTOR_HYPHEN_TO_MINUS_ON,
    B_AAT_LAYOUT_FEATURE_SELECTOR_HYPHEN_TO_MINUS_OFF,
    B_AAT_LAYOUT_FEATURE_SELECTOR_ASTERISK_TO_MULTIPLY_ON,
    B_AAT_LAYOUT_FEATURE_SELECTOR_ASTERISK_TO_MULTIPLY_OFF,
    B_AAT_LAYOUT_FEATURE_SELECTOR_SLASH_TO_DIVIDE_ON,
    B_AAT_LAYOUT_FEATURE_SELECTOR_SLASH_TO_DIVIDE_OFF,
    B_AAT_LAYOUT_FEATURE_SELECTOR_INEQUALITY_LIGATURES_ON,
    B_AAT_LAYOUT_FEATURE_SELECTOR_INEQUALITY_LIGATURES_OFF,
    B_AAT_LAYOUT_FEATURE_SELECTOR_EXPONENTS_ON,
    B_AAT_LAYOUT_FEATURE_SELECTOR_EXPONENTS_OFF,
    B_AAT_LAYOUT_FEATURE_SELECTOR_MATHEMATICAL_GREEK_ON,
    B_AAT_LAYOUT_FEATURE_SELECTOR_MATHEMATICAL_GREEK_OFF,
    B_AAT_LAYOUT_FEATURE_SELECTOR_NO_ORNAMENTS,
    B_AAT_LAYOUT_FEATURE_SELECTOR_DINGBATS,
    B_AAT_LAYOUT_FEATURE_SELECTOR_PI_CHARACTERS,
    B_AAT_LAYOUT_FEATURE_SELECTOR_FLEURONS,
    B_AAT_LAYOUT_FEATURE_SELECTOR_DECORATIVE_BORDERS,
    B_AAT_LAYOUT_FEATURE_SELECTOR_INTERNATIONAL_SYMBOLS,
    B_AAT_LAYOUT_FEATURE_SELECTOR_MATH_SYMBOLS,
    B_AAT_LAYOUT_FEATURE_SELECTOR_NO_ALTERNATES,
    B_AAT_LAYOUT_FEATURE_SELECTOR_DESIGN_LEVEL1,
    B_AAT_LAYOUT_FEATURE_SELECTOR_DESIGN_LEVEL2,
    B_AAT_LAYOUT_FEATURE_SELECTOR_DESIGN_LEVEL3,
    B_AAT_LAYOUT_FEATURE_SELECTOR_DESIGN_LEVEL4,
    B_AAT_LAYOUT_FEATURE_SELECTOR_DESIGN_LEVEL5,
    B_AAT_LAYOUT_FEATURE_SELECTOR_NO_STYLE_OPTIONS,
    B_AAT_LAYOUT_FEATURE_SELECTOR_DISPLAY_TEXT,
    B_AAT_LAYOUT_FEATURE_SELECTOR_ENGRAVED_TEXT,
    B_AAT_LAYOUT_FEATURE_SELECTOR_ILLUMINATED_CAPS,
    B_AAT_LAYOUT_FEATURE_SELECTOR_TITLING_CAPS,
    B_AAT_LAYOUT_FEATURE_SELECTOR_TALL_CAPS,
    B_AAT_LAYOUT_FEATURE_SELECTOR_TRADITIONAL_CHARACTERS,
    B_AAT_LAYOUT_FEATURE_SELECTOR_SIMPLIFIED_CHARACTERS,
    B_AAT_LAYOUT_FEATURE_SELECTOR_JIS1978_CHARACTERS,
    B_AAT_LAYOUT_FEATURE_SELECTOR_JIS1983_CHARACTERS,
    B_AAT_LAYOUT_FEATURE_SELECTOR_JIS1990_CHARACTERS,
    B_AAT_LAYOUT_FEATURE_SELECTOR_TRADITIONAL_ALT_ONE,
    B_AAT_LAYOUT_FEATURE_SELECTOR_TRADITIONAL_ALT_TWO,
    B_AAT_LAYOUT_FEATURE_SELECTOR_TRADITIONAL_ALT_THREE,
    B_AAT_LAYOUT_FEATURE_SELECTOR_TRADITIONAL_ALT_FOUR,
    B_AAT_LAYOUT_FEATURE_SELECTOR_TRADITIONAL_ALT_FIVE,
    B_AAT_LAYOUT_FEATURE_SELECTOR_EXPERT_CHARACTERS,
    B_AAT_LAYOUT_FEATURE_SELECTOR_JIS2004_CHARACTERS,
    B_AAT_LAYOUT_FEATURE_SELECTOR_HOJO_CHARACTERS,
    B_AAT_LAYOUT_FEATURE_SELECTOR_NLCCHARACTERS,
    B_AAT_LAYOUT_FEATURE_SELECTOR_TRADITIONAL_NAMES_CHARACTERS,
    B_AAT_LAYOUT_FEATURE_SELECTOR_LOWER_CASE_NUMBERS,
    B_AAT_LAYOUT_FEATURE_SELECTOR_UPPER_CASE_NUMBERS,
    B_AAT_LAYOUT_FEATURE_SELECTOR_PROPORTIONAL_TEXT,
    B_AAT_LAYOUT_FEATURE_SELECTOR_MONOSPACED_TEXT,
    B_AAT_LAYOUT_FEATURE_SELECTOR_HALF_WIDTH_TEXT,
    B_AAT_LAYOUT_FEATURE_SELECTOR_THIRD_WIDTH_TEXT,
    B_AAT_LAYOUT_FEATURE_SELECTOR_QUARTER_WIDTH_TEXT,
    B_AAT_LAYOUT_FEATURE_SELECTOR_ALT_PROPORTIONAL_TEXT,
    B_AAT_LAYOUT_FEATURE_SELECTOR_ALT_HALF_WIDTH_TEXT,
    B_AAT_LAYOUT_FEATURE_SELECTOR_NO_TRANSLITERATION,
    B_AAT_LAYOUT_FEATURE_SELECTOR_HANJA_TO_HANGUL,
    B_AAT_LAYOUT_FEATURE_SELECTOR_HIRAGANA_TO_KATAKANA,
    B_AAT_LAYOUT_FEATURE_SELECTOR_KATAKANA_TO_HIRAGANA,
    B_AAT_LAYOUT_FEATURE_SELECTOR_KANA_TO_ROMANIZATION,
    B_AAT_LAYOUT_FEATURE_SELECTOR_ROMANIZATION_TO_HIRAGANA,
    B_AAT_LAYOUT_FEATURE_SELECTOR_ROMANIZATION_TO_KATAKANA,
    B_AAT_LAYOUT_FEATURE_SELECTOR_HANJA_TO_HANGUL_ALT_ONE,
    B_AAT_LAYOUT_FEATURE_SELECTOR_HANJA_TO_HANGUL_ALT_TWO,
    B_AAT_LAYOUT_FEATURE_SELECTOR_HANJA_TO_HANGUL_ALT_THREE,
    B_AAT_LAYOUT_FEATURE_SELECTOR_NO_ANNOTATION,
    B_AAT_LAYOUT_FEATURE_SELECTOR_BOX_ANNOTATION,
    B_AAT_LAYOUT_FEATURE_SELECTOR_ROUNDED_BOX_ANNOTATION,
    B_AAT_LAYOUT_FEATURE_SELECTOR_CIRCLE_ANNOTATION,
    B_AAT_LAYOUT_FEATURE_SELECTOR_INVERTED_CIRCLE_ANNOTATION,
    B_AAT_LAYOUT_FEATURE_SELECTOR_PARENTHESIS_ANNOTATION,
    B_AAT_LAYOUT_FEATURE_SELECTOR_PERIOD_ANNOTATION,
    B_AAT_LAYOUT_FEATURE_SELECTOR_ROMAN_NUMERAL_ANNOTATION,
    B_AAT_LAYOUT_FEATURE_SELECTOR_DIAMOND_ANNOTATION,
    B_AAT_LAYOUT_FEATURE_SELECTOR_INVERTED_BOX_ANNOTATION,
    B_AAT_LAYOUT_FEATURE_SELECTOR_INVERTED_ROUNDED_BOX_ANNOTATION,
    B_AAT_LAYOUT_FEATURE_SELECTOR_FULL_WIDTH_KANA,
    B_AAT_LAYOUT_FEATURE_SELECTOR_PROPORTIONAL_KANA,
    B_AAT_LAYOUT_FEATURE_SELECTOR_FULL_WIDTH_IDEOGRAPHS,
    B_AAT_LAYOUT_FEATURE_SELECTOR_PROPORTIONAL_IDEOGRAPHS,
    B_AAT_LAYOUT_FEATURE_SELECTOR_HALF_WIDTH_IDEOGRAPHS,
    B_AAT_LAYOUT_FEATURE_SELECTOR_CANONICAL_COMPOSITION_ON,
    B_AAT_LAYOUT_FEATURE_SELECTOR_CANONICAL_COMPOSITION_OFF,
    B_AAT_LAYOUT_FEATURE_SELECTOR_COMPATIBILITY_COMPOSITION_ON,
    B_AAT_LAYOUT_FEATURE_SELECTOR_COMPATIBILITY_COMPOSITION_OFF,
    B_AAT_LAYOUT_FEATURE_SELECTOR_TRANSCODING_COMPOSITION_ON,
    B_AAT_LAYOUT_FEATURE_SELECTOR_TRANSCODING_COMPOSITION_OFF,
    B_AAT_LAYOUT_FEATURE_SELECTOR_NO_RUBY_KANA,
    B_AAT_LAYOUT_FEATURE_SELECTOR_RUBY_KANA,
    B_AAT_LAYOUT_FEATURE_SELECTOR_RUBY_KANA_ON,
    B_AAT_LAYOUT_FEATURE_SELECTOR_RUBY_KANA_OFF,
    B_AAT_LAYOUT_FEATURE_SELECTOR_NO_CJK_SYMBOL_ALTERNATIVES,
    B_AAT_LAYOUT_FEATURE_SELECTOR_CJK_SYMBOL_ALT_ONE,
    B_AAT_LAYOUT_FEATURE_SELECTOR_CJK_SYMBOL_ALT_TWO,
    B_AAT_LAYOUT_FEATURE_SELECTOR_CJK_SYMBOL_ALT_THREE,
    B_AAT_LAYOUT_FEATURE_SELECTOR_CJK_SYMBOL_ALT_FOUR,
    B_AAT_LAYOUT_FEATURE_SELECTOR_CJK_SYMBOL_ALT_FIVE,
    B_AAT_LAYOUT_FEATURE_SELECTOR_NO_IDEOGRAPHIC_ALTERNATIVES,
    B_AAT_LAYOUT_FEATURE_SELECTOR_IDEOGRAPHIC_ALT_ONE,
    B_AAT_LAYOUT_FEATURE_SELECTOR_IDEOGRAPHIC_ALT_TWO,
    B_AAT_LAYOUT_FEATURE_SELECTOR_IDEOGRAPHIC_ALT_THREE,
    B_AAT_LAYOUT_FEATURE_SELECTOR_IDEOGRAPHIC_ALT_FOUR,
    B_AAT_LAYOUT_FEATURE_SELECTOR_IDEOGRAPHIC_ALT_FIVE,
    B_AAT_LAYOUT_FEATURE_SELECTOR_CJK_VERTICAL_ROMAN_CENTERED,
    B_AAT_LAYOUT_FEATURE_SELECTOR_CJK_VERTICAL_ROMAN_HBASELINE,
    B_AAT_LAYOUT_FEATURE_SELECTOR_NO_CJK_ITALIC_ROMAN,
    B_AAT_LAYOUT_FEATURE_SELECTOR_CJK_ITALIC_ROMAN,
    B_AAT_LAYOUT_FEATURE_SELECTOR_CJK_ITALIC_ROMAN_ON,
    B_AAT_LAYOUT_FEATURE_SELECTOR_CJK_ITALIC_ROMAN_OFF,
    B_AAT_LAYOUT_FEATURE_SELECTOR_CASE_SENSITIVE_LAYOUT_ON,
    B_AAT_LAYOUT_FEATURE_SELECTOR_CASE_SENSITIVE_LAYOUT_OFF,
    B_AAT_LAYOUT_FEATURE_SELECTOR_CASE_SENSITIVE_SPACING_ON,
    B_AAT_LAYOUT_FEATURE_SELECTOR_CASE_SENSITIVE_SPACING_OFF,
    B_AAT_LAYOUT_FEATURE_SELECTOR_ALTERNATE_HORIZ_KANA_ON,
    B_AAT_LAYOUT_FEATURE_SELECTOR_ALTERNATE_HORIZ_KANA_OFF,
    B_AAT_LAYOUT_FEATURE_SELECTOR_ALTERNATE_VERT_KANA_ON,
    B_AAT_LAYOUT_FEATURE_SELECTOR_ALTERNATE_VERT_KANA_OFF,
    B_AAT_LAYOUT_FEATURE_SELECTOR_NO_STYLISTIC_ALTERNATES,
    B_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_ONE_ON,
    B_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_ONE_OFF,
    B_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_TWO_ON,
    B_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_TWO_OFF,
    B_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_THREE_ON,
    B_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_THREE_OFF,
    B_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_FOUR_ON,
    B_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_FOUR_OFF,
    B_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_FIVE_ON,
    B_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_FIVE_OFF,
    B_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_SIX_ON,
    B_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_SIX_OFF,
    B_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_SEVEN_ON,
    B_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_SEVEN_OFF,
    B_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_EIGHT_ON,
    B_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_EIGHT_OFF,
    B_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_NINE_ON,
    B_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_NINE_OFF,
    B_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_TEN_ON,
    B_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_TEN_OFF,
    B_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_ELEVEN_ON,
    B_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_ELEVEN_OFF,
    B_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_TWELVE_ON,
    B_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_TWELVE_OFF,
    B_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_THIRTEEN_ON,
    B_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_THIRTEEN_OFF,
    B_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_FOURTEEN_ON,
    B_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_FOURTEEN_OFF,
    B_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_FIFTEEN_ON,
    B_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_FIFTEEN_OFF,
    B_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_SIXTEEN_ON,
    B_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_SIXTEEN_OFF,
    B_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_SEVENTEEN_ON,
    B_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_SEVENTEEN_OFF,
    B_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_EIGHTEEN_ON,
    B_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_EIGHTEEN_OFF,
    B_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_NINETEEN_ON,
    B_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_NINETEEN_OFF,
    B_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_TWENTY_ON,
    B_AAT_LAYOUT_FEATURE_SELECTOR_STYLISTIC_ALT_TWENTY_OFF,
    B_AAT_LAYOUT_FEATURE_SELECTOR_CONTEXTUAL_ALTERNATES_ON,
    B_AAT_LAYOUT_FEATURE_SELECTOR_CONTEXTUAL_ALTERNATES_OFF,
    B_AAT_LAYOUT_FEATURE_SELECTOR_SWASH_ALTERNATES_ON,
    B_AAT_LAYOUT_FEATURE_SELECTOR_SWASH_ALTERNATES_OFF,
    B_AAT_LAYOUT_FEATURE_SELECTOR_CONTEXTUAL_SWASH_ALTERNATES_ON,
    B_AAT_LAYOUT_FEATURE_SELECTOR_CONTEXTUAL_SWASH_ALTERNATES_OFF,
    B_AAT_LAYOUT_FEATURE_SELECTOR_DEFAULT_LOWER_CASE,
    B_AAT_LAYOUT_FEATURE_SELECTOR_LOWER_CASE_SMALL_CAPS,
    B_AAT_LAYOUT_FEATURE_SELECTOR_LOWER_CASE_PETITE_CAPS,
    B_AAT_LAYOUT_FEATURE_SELECTOR_DEFAULT_UPPER_CASE,
    B_AAT_LAYOUT_FEATURE_SELECTOR_UPPER_CASE_SMALL_CAPS,
    B_AAT_LAYOUT_FEATURE_SELECTOR_UPPER_CASE_PETITE_CAPS,
    B_AAT_LAYOUT_FEATURE_SELECTOR_HALF_WIDTH_CJK_ROMAN,
    B_AAT_LAYOUT_FEATURE_SELECTOR_PROPORTIONAL_CJK_ROMAN,
    B_AAT_LAYOUT_FEATURE_SELECTOR_DEFAULT_CJK_ROMAN,
    B_AAT_LAYOUT_FEATURE_SELECTOR_FULL_WIDTH_CJK_ROMAN,
}
export enum aat_layout_feature_type_t {
    B_AAT_LAYOUT_FEATURE_TYPE_INVALID,
    B_AAT_LAYOUT_FEATURE_TYPE_ALL_TYPOGRAPHIC,
    B_AAT_LAYOUT_FEATURE_TYPE_LIGATURES,
    B_AAT_LAYOUT_FEATURE_TYPE_CURSIVE_CONNECTION,
    B_AAT_LAYOUT_FEATURE_TYPE_LETTER_CASE,
    B_AAT_LAYOUT_FEATURE_TYPE_VERTICAL_SUBSTITUTION,
    B_AAT_LAYOUT_FEATURE_TYPE_LINGUISTIC_REARRANGEMENT,
    B_AAT_LAYOUT_FEATURE_TYPE_NUMBER_SPACING,
    B_AAT_LAYOUT_FEATURE_TYPE_SMART_SWASH_TYPE,
    B_AAT_LAYOUT_FEATURE_TYPE_DIACRITICS_TYPE,
    B_AAT_LAYOUT_FEATURE_TYPE_VERTICAL_POSITION,
    B_AAT_LAYOUT_FEATURE_TYPE_FRACTIONS,
    B_AAT_LAYOUT_FEATURE_TYPE_OVERLAPPING_CHARACTERS_TYPE,
    B_AAT_LAYOUT_FEATURE_TYPE_TYPOGRAPHIC_EXTRAS,
    B_AAT_LAYOUT_FEATURE_TYPE_MATHEMATICAL_EXTRAS,
    B_AAT_LAYOUT_FEATURE_TYPE_ORNAMENT_SETS_TYPE,
    B_AAT_LAYOUT_FEATURE_TYPE_CHARACTER_ALTERNATIVES,
    B_AAT_LAYOUT_FEATURE_TYPE_DESIGN_COMPLEXITY_TYPE,
    B_AAT_LAYOUT_FEATURE_TYPE_STYLE_OPTIONS,
    B_AAT_LAYOUT_FEATURE_TYPE_CHARACTER_SHAPE,
    B_AAT_LAYOUT_FEATURE_TYPE_NUMBER_CASE,
    B_AAT_LAYOUT_FEATURE_TYPE_TEXT_SPACING,
    B_AAT_LAYOUT_FEATURE_TYPE_TRANSLITERATION,
    B_AAT_LAYOUT_FEATURE_TYPE_ANNOTATION_TYPE,
    B_AAT_LAYOUT_FEATURE_TYPE_KANA_SPACING_TYPE,
    B_AAT_LAYOUT_FEATURE_TYPE_IDEOGRAPHIC_SPACING_TYPE,
    B_AAT_LAYOUT_FEATURE_TYPE_UNICODE_DECOMPOSITION_TYPE,
    B_AAT_LAYOUT_FEATURE_TYPE_RUBY_KANA,
    B_AAT_LAYOUT_FEATURE_TYPE_CJK_SYMBOL_ALTERNATIVES_TYPE,
    B_AAT_LAYOUT_FEATURE_TYPE_IDEOGRAPHIC_ALTERNATIVES_TYPE,
    B_AAT_LAYOUT_FEATURE_TYPE_CJK_VERTICAL_ROMAN_PLACEMENT_TYPE,
    B_AAT_LAYOUT_FEATURE_TYPE_ITALIC_CJK_ROMAN,
    B_AAT_LAYOUT_FEATURE_TYPE_CASE_SENSITIVE_LAYOUT,
    B_AAT_LAYOUT_FEATURE_TYPE_ALTERNATE_KANA,
    B_AAT_LAYOUT_FEATURE_TYPE_STYLISTIC_ALTERNATIVES,
    B_AAT_LAYOUT_FEATURE_TYPE_CONTEXTUAL_ALTERNATIVES,
    B_AAT_LAYOUT_FEATURE_TYPE_LOWER_CASE,
    B_AAT_LAYOUT_FEATURE_TYPE_UPPER_CASE,
    B_AAT_LAYOUT_FEATURE_TYPE_LANGUAGE_TAG_TYPE,
    B_AAT_LAYOUT_FEATURE_TYPE_CJK_ROMAN_SPACING_TYPE,
}
export enum buffer_diff_flags_t {
    EQUAL,
    CONTENT_TYPE_MISMATCH,
    LENGTH_MISMATCH,
    NOTDEF_PRESENT,
    DOTTED_CIRCLE_PRESENT,
    CODEPOINT_MISMATCH,
    CLUSTER_MISMATCH,
    GLYPH_FLAGS_MISMATCH,
    POSITION_MISMATCH,
}
export enum buffer_flags_t {
    DEFAULT,
    BOT,
    EOT,
    PRESERVE_DEFAULT_IGNORABLES,
    REMOVE_DEFAULT_IGNORABLES,
    DO_NOT_INSERT_DOTTED_CIRCLE,
    VERIFY,
    PRODUCE_UNSAFE_TO_CONCAT,
    PRODUCE_SAFE_TO_INSERT_TATWEEL,
    DEFINED,
}
export enum buffer_serialize_flags_t {
    DEFAULT,
    NO_CLUSTERS,
    NO_POSITIONS,
    NO_GLYPH_NAMES,
    GLYPH_EXTENTS,
    GLYPH_FLAGS,
    NO_ADVANCES,
    DEFINED,
}
export enum buffer_serialize_format_t {
    TEXT,
    JSON,
    INVALID,
}
export enum glyph_flags_t {
    UNSAFE_TO_BREAK,
    UNSAFE_TO_CONCAT,
    SAFE_TO_INSERT_TATWEEL,
    DEFINED,
}
export enum ot_color_palette_flags_t {
    DEFAULT,
    USABLE_WITH_LIGHT_BACKGROUND,
    USABLE_WITH_DARK_BACKGROUND,
}
export enum ot_layout_baseline_tag_t {
    B_OT_LAYOUT_BASELINE_TAG_ROMAN,
    B_OT_LAYOUT_BASELINE_TAG_HANGING,
    B_OT_LAYOUT_BASELINE_TAG_IDEO_FACE_BOTTOM_OR_LEFT,
    B_OT_LAYOUT_BASELINE_TAG_IDEO_FACE_TOP_OR_RIGHT,
    B_OT_LAYOUT_BASELINE_TAG_IDEO_FACE_CENTRAL,
    B_OT_LAYOUT_BASELINE_TAG_IDEO_EMBOX_BOTTOM_OR_LEFT,
    B_OT_LAYOUT_BASELINE_TAG_IDEO_EMBOX_TOP_OR_RIGHT,
    B_OT_LAYOUT_BASELINE_TAG_IDEO_EMBOX_CENTRAL,
    B_OT_LAYOUT_BASELINE_TAG_MATH,
}
export enum ot_math_glyph_part_flags_t {
    OT_MATH_GLYPH_PART_FLAG_EXTENDER,
}
export enum ot_meta_tag_t {
    B_OT_META_TAG_DESIGN_LANGUAGES,
    B_OT_META_TAG_SUPPORTED_LANGUAGES,
}
export enum ot_metrics_tag_t {
    B_OT_METRICS_TAG_HORIZONTAL_ASCENDER,
    B_OT_METRICS_TAG_HORIZONTAL_DESCENDER,
    B_OT_METRICS_TAG_HORIZONTAL_LINE_GAP,
    B_OT_METRICS_TAG_HORIZONTAL_CLIPPING_ASCENT,
    B_OT_METRICS_TAG_HORIZONTAL_CLIPPING_DESCENT,
    B_OT_METRICS_TAG_VERTICAL_ASCENDER,
    B_OT_METRICS_TAG_VERTICAL_DESCENDER,
    B_OT_METRICS_TAG_VERTICAL_LINE_GAP,
    B_OT_METRICS_TAG_HORIZONTAL_CARET_RISE,
    B_OT_METRICS_TAG_HORIZONTAL_CARET_RUN,
    B_OT_METRICS_TAG_HORIZONTAL_CARET_OFFSET,
    B_OT_METRICS_TAG_VERTICAL_CARET_RISE,
    B_OT_METRICS_TAG_VERTICAL_CARET_RUN,
    B_OT_METRICS_TAG_VERTICAL_CARET_OFFSET,
    B_OT_METRICS_TAG_X_HEIGHT,
    B_OT_METRICS_TAG_CAP_HEIGHT,
    B_OT_METRICS_TAG_SUBSCRIPT_EM_X_SIZE,
    B_OT_METRICS_TAG_SUBSCRIPT_EM_Y_SIZE,
    B_OT_METRICS_TAG_SUBSCRIPT_EM_X_OFFSET,
    B_OT_METRICS_TAG_SUBSCRIPT_EM_Y_OFFSET,
    B_OT_METRICS_TAG_SUPERSCRIPT_EM_X_SIZE,
    B_OT_METRICS_TAG_SUPERSCRIPT_EM_Y_SIZE,
    B_OT_METRICS_TAG_SUPERSCRIPT_EM_X_OFFSET,
    B_OT_METRICS_TAG_SUPERSCRIPT_EM_Y_OFFSET,
    B_OT_METRICS_TAG_STRIKEOUT_SIZE,
    B_OT_METRICS_TAG_STRIKEOUT_OFFSET,
    B_OT_METRICS_TAG_UNDERLINE_SIZE,
    B_OT_METRICS_TAG_UNDERLINE_OFFSET,
}
export enum ot_var_axis_flags_t {
    B_OT_VAR_AXIS_FLAG_HIDDEN,
}
export enum script_t {
    B_SCRIPT_COMMON,
    B_SCRIPT_INHERITED,
    B_SCRIPT_UNKNOWN,
    B_SCRIPT_ARABIC,
    B_SCRIPT_ARMENIAN,
    B_SCRIPT_BENGALI,
    B_SCRIPT_CYRILLIC,
    B_SCRIPT_DEVANAGARI,
    B_SCRIPT_GEORGIAN,
    B_SCRIPT_GREEK,
    B_SCRIPT_GUJARATI,
    B_SCRIPT_GURMUKHI,
    B_SCRIPT_HANGUL,
    B_SCRIPT_HAN,
    B_SCRIPT_HEBREW,
    B_SCRIPT_HIRAGANA,
    B_SCRIPT_KANNADA,
    B_SCRIPT_KATAKANA,
    B_SCRIPT_LAO,
    B_SCRIPT_LATIN,
    B_SCRIPT_MALAYALAM,
    B_SCRIPT_ORIYA,
    B_SCRIPT_TAMIL,
    B_SCRIPT_TELUGU,
    B_SCRIPT_THAI,
    B_SCRIPT_TIBETAN,
    B_SCRIPT_BOPOMOFO,
    B_SCRIPT_BRAILLE,
    B_SCRIPT_CANADIAN_SYLLABICS,
    B_SCRIPT_CHEROKEE,
    B_SCRIPT_ETHIOPIC,
    B_SCRIPT_KHMER,
    B_SCRIPT_MONGOLIAN,
    B_SCRIPT_MYANMAR,
    B_SCRIPT_OGHAM,
    B_SCRIPT_RUNIC,
    B_SCRIPT_SINHALA,
    B_SCRIPT_SYRIAC,
    B_SCRIPT_THAANA,
    B_SCRIPT_YI,
    B_SCRIPT_DESERET,
    B_SCRIPT_GOTHIC,
    B_SCRIPT_OLD_ITALIC,
    B_SCRIPT_BUHID,
    B_SCRIPT_HANUNOO,
    B_SCRIPT_TAGALOG,
    B_SCRIPT_TAGBANWA,
    B_SCRIPT_CYPRIOT,
    B_SCRIPT_LIMBU,
    B_SCRIPT_LINEAR_B,
    B_SCRIPT_OSMANYA,
    B_SCRIPT_SHAVIAN,
    B_SCRIPT_TAI_LE,
    B_SCRIPT_UGARITIC,
    B_SCRIPT_BUGINESE,
    B_SCRIPT_COPTIC,
    B_SCRIPT_GLAGOLITIC,
    B_SCRIPT_KHAROSHTHI,
    B_SCRIPT_NEW_TAI_LUE,
    B_SCRIPT_OLD_PERSIAN,
    B_SCRIPT_SYLOTI_NAGRI,
    B_SCRIPT_TIFINAGH,
    B_SCRIPT_BALINESE,
    B_SCRIPT_CUNEIFORM,
    B_SCRIPT_NKO,
    B_SCRIPT_PHAGS_PA,
    B_SCRIPT_PHOENICIAN,
    B_SCRIPT_CARIAN,
    B_SCRIPT_CHAM,
    B_SCRIPT_KAYAH_LI,
    B_SCRIPT_LEPCHA,
    B_SCRIPT_LYCIAN,
    B_SCRIPT_LYDIAN,
    B_SCRIPT_OL_CHIKI,
    B_SCRIPT_REJANG,
    B_SCRIPT_SAURASHTRA,
    B_SCRIPT_SUNDANESE,
    B_SCRIPT_VAI,
    B_SCRIPT_AVESTAN,
    B_SCRIPT_BAMUM,
    B_SCRIPT_EGYPTIAN_HIEROGLYPHS,
    B_SCRIPT_IMPERIAL_ARAMAIC,
    B_SCRIPT_INSCRIPTIONAL_PAHLAVI,
    B_SCRIPT_INSCRIPTIONAL_PARTHIAN,
    B_SCRIPT_JAVANESE,
    B_SCRIPT_KAITHI,
    B_SCRIPT_LISU,
    B_SCRIPT_MEETEI_MAYEK,
    B_SCRIPT_OLD_SOUTH_ARABIAN,
    B_SCRIPT_OLD_TURKIC,
    B_SCRIPT_SAMARITAN,
    B_SCRIPT_TAI_THAM,
    B_SCRIPT_TAI_VIET,
    B_SCRIPT_BATAK,
    B_SCRIPT_BRAHMI,
    B_SCRIPT_MANDAIC,
    B_SCRIPT_CHAKMA,
    B_SCRIPT_MEROITIC_CURSIVE,
    B_SCRIPT_MEROITIC_HIEROGLYPHS,
    B_SCRIPT_MIAO,
    B_SCRIPT_SHARADA,
    B_SCRIPT_SORA_SOMPENG,
    B_SCRIPT_TAKRI,
    B_SCRIPT_BASSA_VAH,
    B_SCRIPT_CAUCASIAN_ALBANIAN,
    B_SCRIPT_DUPLOYAN,
    B_SCRIPT_ELBASAN,
    B_SCRIPT_GRANTHA,
    B_SCRIPT_KHOJKI,
    B_SCRIPT_KHUDAWADI,
    B_SCRIPT_LINEAR_A,
    B_SCRIPT_MAHAJANI,
    B_SCRIPT_MANICHAEAN,
    B_SCRIPT_MENDE_KIKAKUI,
    B_SCRIPT_MODI,
    B_SCRIPT_MRO,
    B_SCRIPT_NABATAEAN,
    B_SCRIPT_OLD_NORTH_ARABIAN,
    B_SCRIPT_OLD_PERMIC,
    B_SCRIPT_PAHAWH_HMONG,
    B_SCRIPT_PALMYRENE,
    B_SCRIPT_PAU_CIN_HAU,
    B_SCRIPT_PSALTER_PAHLAVI,
    B_SCRIPT_SIDDHAM,
    B_SCRIPT_TIRHUTA,
    B_SCRIPT_WARANG_CITI,
    B_SCRIPT_AHOM,
    B_SCRIPT_ANATOLIAN_HIEROGLYPHS,
    B_SCRIPT_HATRAN,
    B_SCRIPT_MULTANI,
    B_SCRIPT_OLD_HUNGARIAN,
    B_SCRIPT_SIGNWRITING,
    B_SCRIPT_ADLAM,
    B_SCRIPT_BHAIKSUKI,
    B_SCRIPT_MARCHEN,
    B_SCRIPT_OSAGE,
    B_SCRIPT_TANGUT,
    B_SCRIPT_NEWA,
    B_SCRIPT_MASARAM_GONDI,
    B_SCRIPT_NUSHU,
    B_SCRIPT_SOYOMBO,
    B_SCRIPT_ZANABAZAR_SQUARE,
    B_SCRIPT_DOGRA,
    B_SCRIPT_GUNJALA_GONDI,
    B_SCRIPT_HANIFI_ROHINGYA,
    B_SCRIPT_MAKASAR,
    B_SCRIPT_MEDEFAIDRIN,
    B_SCRIPT_OLD_SOGDIAN,
    B_SCRIPT_SOGDIAN,
    B_SCRIPT_ELYMAIC,
    B_SCRIPT_NANDINAGARI,
    B_SCRIPT_NYIAKENG_PUACHUE_HMONG,
    B_SCRIPT_WANCHO,
    B_SCRIPT_CHORASMIAN,
    B_SCRIPT_DIVES_AKURU,
    B_SCRIPT_KHITAN_SMALL_SCRIPT,
    B_SCRIPT_YEZIDI,
    B_SCRIPT_CYPRO_MINOAN,
    B_SCRIPT_OLD_UYGHUR,
    B_SCRIPT_TANGSA,
    B_SCRIPT_TOTO,
    B_SCRIPT_VITHKUQI,
    B_SCRIPT_MATH,
    B_SCRIPT_KAWI,
    B_SCRIPT_NAG_MUNDARI,
    B_SCRIPT_GARAY,
    B_SCRIPT_GURUNG_KHEMA,
    B_SCRIPT_KIRAT_RAI,
    B_SCRIPT_OL_ONAL,
    B_SCRIPT_SUNUWAR,
    B_SCRIPT_TODHRI,
    B_SCRIPT_TULU_TIGALARI,
    B_SCRIPT_BERIA_ERFE,
    B_SCRIPT_SIDETIC,
    B_SCRIPT_TAI_YO,
    B_SCRIPT_TOLONG_SIKI,
    B_SCRIPT_INVALID,
}
export enum style_tag_t {
    B_STYLE_TAG_ITALIC,
    B_STYLE_TAG_OPTICAL_SIZE,
    B_STYLE_TAG_SLANT_ANGLE,
    B_STYLE_TAG_SLANT_RATIO,
    B_STYLE_TAG_WIDTH,
    B_STYLE_TAG_WEIGHT,
}
export const AAT_LAYOUT_NO_SELECTOR_INDEX: number
export const BUFFER_REPLACEMENT_CODEPOINT_DEFAULT: number
export const CODEPOINT_INVALID: codepoint_t
export const FEATURE_GLOBAL_START: number
export const FONT_NO_VAR_NAMED_INSTANCE: number
export const LANGUAGE_INVALID: language_t
export const OT_LAYOUT_DEFAULT_LANGUAGE_INDEX: number
export const OT_LAYOUT_NO_FEATURE_INDEX: number
export const OT_LAYOUT_NO_SCRIPT_INDEX: number
export const OT_LAYOUT_NO_VARIATIONS_INDEX: number
export const OT_MAX_TAGS_PER_LANGUAGE: number
export const OT_MAX_TAGS_PER_SCRIPT: number
export const OT_VAR_NO_AXIS_INDEX: number
export const UNICODE_COMBINING_CLASS_CCC133: number
export const UNICODE_MAX: number
export const UNICODE_MAX_DECOMPOSITION_LEN: number
export const VERSION_MAJOR: number
export const VERSION_MICRO: number
export const VERSION_MINOR: number
export const VERSION_STRING: string
export function aatLayoutFeatureTypeGetNameId(face: face_t, featureType: aat_layout_feature_type_t): ot_name_id_t
export function aatLayoutFeatureTypeGetSelectorInfos(face: face_t, featureType: aat_layout_feature_type_t, startOffset: number): [ /* returnType */ number, /* selectors */ aat_layout_feature_selector_info_t[] | null, /* defaultIndex */ number | null ]
export function aatLayoutGetFeatureTypes(face: face_t, startOffset: number): [ /* returnType */ number, /* features */ aat_layout_feature_type_t[] ]
export function aatLayoutHasPositioning(face: face_t): bool_t
export function aatLayoutHasSubstitution(face: face_t): bool_t
export function aatLayoutHasTracking(face: face_t): bool_t
export function blobCopyWritableOrFail(blob: blob_t): blob_t
export function blobCreateFromFile(fileName: string): blob_t
export function blobCreateFromFileOrFail(fileName: string): blob_t
export function blobCreateSubBlob(parent: blob_t, offset: number, length: number): blob_t
export function blobGetData(blob: blob_t): string[] | null
export function blobGetDataWritable(blob: blob_t): string[]
export function blobGetEmpty(): blob_t
export function blobGetLength(blob: blob_t): number
export function blobIsImmutable(blob: blob_t): bool_t
export function blobMakeImmutable(blob: blob_t): void
export function bufferAdd(buffer: buffer_t, codepoint: codepoint_t, cluster: number): void
export function bufferAddCodepoints(buffer: buffer_t, text: codepoint_t[], itemOffset: number, itemLength: number): void
export function bufferAddLatin1(buffer: buffer_t, text: any, itemOffset: number, itemLength: number): void
export function bufferAddUtf16(buffer: buffer_t, text: number[], itemOffset: number, itemLength: number): void
export function bufferAddUtf32(buffer: buffer_t, text: number[], itemOffset: number, itemLength: number): void
export function bufferAddUtf8(buffer: buffer_t, text: any, itemOffset: number, itemLength: number): void
export function bufferAllocationSuccessful(buffer: buffer_t): bool_t
export function bufferAppend(buffer: buffer_t, source: buffer_t, start: number, end: number): void
export function bufferClearContents(buffer: buffer_t): void
export function bufferCreate(): buffer_t
export function bufferCreateSimilar(src: buffer_t): buffer_t
export function bufferDeserializeGlyphs(buffer: buffer_t, buf: string[], font: font_t | null, format: buffer_serialize_format_t): [ /* returnType */ bool_t, /* endPtr */ string | null ]
export function bufferDeserializeUnicode(buffer: buffer_t, buf: string[], format: buffer_serialize_format_t): [ /* returnType */ bool_t, /* endPtr */ string | null ]
export function bufferDiff(buffer: buffer_t, reference: buffer_t, dottedcircleGlyph: codepoint_t, positionFuzz: number): buffer_diff_flags_t
export function bufferGetClusterLevel(buffer: buffer_t): buffer_cluster_level_t
export function bufferGetContentType(buffer: buffer_t): buffer_content_type_t
export function bufferGetDirection(buffer: buffer_t): direction_t
export function bufferGetEmpty(): buffer_t
export function bufferGetFlags(buffer: buffer_t): buffer_flags_t
export function bufferGetGlyphInfos(buffer: buffer_t): glyph_info_t[]
export function bufferGetGlyphPositions(buffer: buffer_t): glyph_position_t[]
export function bufferGetInvisibleGlyph(buffer: buffer_t): codepoint_t
export function bufferGetLanguage(buffer: buffer_t): language_t
export function bufferGetLength(buffer: buffer_t): number
export function bufferGetNotFoundGlyph(buffer: buffer_t): codepoint_t
export function bufferGetNotFoundVariationSelectorGlyph(buffer: buffer_t): codepoint_t
export function bufferGetRandomState(buffer: buffer_t): number
export function bufferGetReplacementCodepoint(buffer: buffer_t): codepoint_t
export function bufferGetScript(buffer: buffer_t): script_t
export function bufferGetSegmentProperties(buffer: buffer_t): /* props */ segment_properties_t
export function bufferGetUnicodeFuncs(buffer: buffer_t): unicode_funcs_t
export function bufferGuessSegmentProperties(buffer: buffer_t): void
export function bufferHasPositions(buffer: buffer_t): bool_t
export function bufferNormalizeGlyphs(buffer: buffer_t): void
export function bufferPreAllocate(buffer: buffer_t, size: number): bool_t
export function bufferReset(buffer: buffer_t): void
export function bufferReverse(buffer: buffer_t): void
export function bufferReverseClusters(buffer: buffer_t): void
export function bufferReverseRange(buffer: buffer_t, start: number, end: number): void
export function bufferSerialize(buffer: buffer_t, start: number, end: number, font: font_t | null, format: buffer_serialize_format_t, flags: buffer_serialize_flags_t): [ /* returnType */ number, /* buf */ any, /* bufConsumed */ number | null ]
export function bufferSerializeFormatFromString(str: any): buffer_serialize_format_t
export function bufferSerializeFormatToString(format: buffer_serialize_format_t): string
export function bufferSerializeGlyphs(buffer: buffer_t, start: number, end: number, font: font_t | null, format: buffer_serialize_format_t, flags: buffer_serialize_flags_t): [ /* returnType */ number, /* buf */ any, /* bufConsumed */ number | null ]
export function bufferSerializeListFormats(): string[]
export function bufferSerializeUnicode(buffer: buffer_t, start: number, end: number, format: buffer_serialize_format_t, flags: buffer_serialize_flags_t): [ /* returnType */ number, /* buf */ any, /* bufConsumed */ number | null ]
export function bufferSetClusterLevel(buffer: buffer_t, clusterLevel: buffer_cluster_level_t): void
export function bufferSetContentType(buffer: buffer_t, contentType: buffer_content_type_t): void
export function bufferSetDirection(buffer: buffer_t, direction: direction_t): void
export function bufferSetFlags(buffer: buffer_t, flags: buffer_flags_t): void
export function bufferSetInvisibleGlyph(buffer: buffer_t, invisible: codepoint_t): void
export function bufferSetLanguage(buffer: buffer_t, language: language_t): void
export function bufferSetLength(buffer: buffer_t, length: number): bool_t
export function bufferSetMessageFunc(buffer: buffer_t, func: buffer_message_func_t): void
export function bufferSetNotFoundGlyph(buffer: buffer_t, notFound: codepoint_t): void
export function bufferSetNotFoundVariationSelectorGlyph(buffer: buffer_t, notFoundVariationSelector: codepoint_t): void
export function bufferSetRandomState(buffer: buffer_t, state: number): void
export function bufferSetReplacementCodepoint(buffer: buffer_t, replacement: codepoint_t): void
export function bufferSetScript(buffer: buffer_t, script: script_t): void
export function bufferSetSegmentProperties(buffer: buffer_t, props: segment_properties_t): void
export function bufferSetUnicodeFuncs(buffer: buffer_t, unicodeFuncs: unicode_funcs_t): void
export function calloc(nmemb: number, size: number): object | null
export function colorGetAlpha(color: color_t): number
export function colorGetBlue(color: color_t): number
export function colorGetGreen(color: color_t): number
export function colorGetRed(color: color_t): number
export function colorLineGetColorStops(colorLine: color_line_t, start: number): [ /* returnType */ number, /* colorStops */ color_stop_t[] | null ]
export function colorLineGetExtend(colorLine: color_line_t): paint_extend_t
export function directionFromString(str: any): direction_t
export function directionToString(direction: direction_t): string
export function drawClosePath(dfuncs: draw_funcs_t, drawData: object | null, st: draw_state_t): void
export function drawCubicTo(dfuncs: draw_funcs_t, drawData: object | null, st: draw_state_t, control1X: number, control1Y: number, control2X: number, control2Y: number, toX: number, toY: number): void
export function drawFuncsCreate(): draw_funcs_t
export function drawFuncsGetEmpty(): draw_funcs_t
export function drawFuncsIsImmutable(dfuncs: draw_funcs_t): bool_t
export function drawFuncsMakeImmutable(dfuncs: draw_funcs_t): void
export function drawFuncsSetClosePathFunc(dfuncs: draw_funcs_t, func: draw_close_path_func_t): void
export function drawFuncsSetCubicToFunc(dfuncs: draw_funcs_t, func: draw_cubic_to_func_t): void
export function drawFuncsSetLineToFunc(dfuncs: draw_funcs_t, func: draw_line_to_func_t): void
export function drawFuncsSetMoveToFunc(dfuncs: draw_funcs_t, func: draw_move_to_func_t): void
export function drawFuncsSetQuadraticToFunc(dfuncs: draw_funcs_t, func: draw_quadratic_to_func_t): void
export function drawLineTo(dfuncs: draw_funcs_t, drawData: object | null, st: draw_state_t, toX: number, toY: number): void
export function drawMoveTo(dfuncs: draw_funcs_t, drawData: object | null, st: draw_state_t, toX: number, toY: number): void
export function drawQuadraticTo(dfuncs: draw_funcs_t, drawData: object | null, st: draw_state_t, controlX: number, controlY: number, toX: number, toY: number): void
export function faceBuilderAddTable(face: face_t, tag: tag_t, blob: blob_t): bool_t
export function faceBuilderCreate(): face_t
export function faceBuilderSortTables(face: face_t, tags: tag_t[]): void
export function faceCollectNominalGlyphMapping(face: face_t): [ /* mapping */ map_t, /* unicodes */ set_t | null ]
export function faceCollectUnicodes(face: face_t): /* out */ set_t
export function faceCollectVariationSelectors(face: face_t): /* out */ set_t
export function faceCollectVariationUnicodes(face: face_t, variationSelector: codepoint_t): /* out */ set_t
export function faceCount(blob: blob_t): number
export function faceCreate(blob: blob_t, index: number): face_t
export function faceCreateForTables(referenceTableFunc: reference_table_func_t): face_t
export function faceCreateFromFileOrFail(fileName: string, index: number): face_t
export function faceCreateFromFileOrFailUsing(fileName: string, index: number, loaderName?: string | null): face_t
export function faceCreateOrFail(blob: blob_t, index: number): face_t
export function faceCreateOrFailUsing(blob: blob_t, index: number, loaderName?: string | null): face_t
export function faceGetEmpty(): face_t
export function faceGetGlyphCount(face: face_t): number
export function faceGetIndex(face: face_t): number
export function faceGetTableTags(face: face_t, startOffset: number): [ /* returnType */ number, /* tableTags */ tag_t[] ]
export function faceGetUpem(face: face_t): number
export function faceIsImmutable(face: face_t): bool_t
export function faceListLoaders(): string[]
export function faceMakeImmutable(face: face_t): void
export function faceReferenceBlob(face: face_t): blob_t
export function faceReferenceTable(face: face_t, tag: tag_t): blob_t
export function faceSetGetTableTagsFunc(face: face_t, func: get_table_tags_func_t): void
export function faceSetGlyphCount(face: face_t, glyphCount: number): void
export function faceSetIndex(face: face_t, index: number): void
export function faceSetUpem(face: face_t, upem: number): void
export function featureFromString(str: any): [ /* returnType */ bool_t, /* feature */ feature_t ]
export function featureToString(feature: feature_t): /* buf */ string[]
export function fontAddGlyphOriginForDirection(font: font_t, glyph: codepoint_t, direction: direction_t, x: position_t, y: position_t): void
export function fontChanged(font: font_t): void
export function fontCreate(face: face_t): font_t
export function fontCreateSubFont(parent: font_t): font_t
export function fontDrawGlyph(font: font_t, glyph: codepoint_t, dfuncs: draw_funcs_t, drawData?: object | null): void
export function fontDrawGlyphOrFail(font: font_t, glyph: codepoint_t, dfuncs: draw_funcs_t, drawData?: object | null): bool_t
export function fontFuncsCreate(): font_funcs_t
export function fontFuncsGetEmpty(): font_funcs_t
export function fontFuncsIsImmutable(ffuncs: font_funcs_t): bool_t
export function fontFuncsMakeImmutable(ffuncs: font_funcs_t): void
export function fontFuncsSetDrawGlyphFunc(ffuncs: font_funcs_t, func: font_draw_glyph_func_t): void
export function fontFuncsSetDrawGlyphOrFailFunc(ffuncs: font_funcs_t, func: font_draw_glyph_or_fail_func_t): void
export function fontFuncsSetFontHExtentsFunc(ffuncs: font_funcs_t, func: font_get_font_h_extents_func_t): void
export function fontFuncsSetFontVExtentsFunc(ffuncs: font_funcs_t, func: font_get_font_v_extents_func_t): void
export function fontFuncsSetGlyphContourPointFunc(ffuncs: font_funcs_t, func: font_get_glyph_contour_point_func_t): void
export function fontFuncsSetGlyphExtentsFunc(ffuncs: font_funcs_t, func: font_get_glyph_extents_func_t): void
export function fontFuncsSetGlyphFromNameFunc(ffuncs: font_funcs_t, func: font_get_glyph_from_name_func_t): void
export function fontFuncsSetGlyphFunc(ffuncs: font_funcs_t, func: font_get_glyph_func_t): void
export function fontFuncsSetGlyphHAdvanceFunc(ffuncs: font_funcs_t, func: font_get_glyph_h_advance_func_t): void
export function fontFuncsSetGlyphHAdvancesFunc(ffuncs: font_funcs_t, func: font_get_glyph_h_advances_func_t): void
export function fontFuncsSetGlyphHKerningFunc(ffuncs: font_funcs_t, func: font_get_glyph_h_kerning_func_t): void
export function fontFuncsSetGlyphHOriginFunc(ffuncs: font_funcs_t, func: font_get_glyph_h_origin_func_t): void
export function fontFuncsSetGlyphHOriginsFunc(ffuncs: font_funcs_t, func: font_get_glyph_h_origins_func_t): void
export function fontFuncsSetGlyphNameFunc(ffuncs: font_funcs_t, func: font_get_glyph_name_func_t): void
export function fontFuncsSetGlyphShapeFunc(ffuncs: font_funcs_t, func: font_get_glyph_shape_func_t): void
export function fontFuncsSetGlyphVAdvanceFunc(ffuncs: font_funcs_t, func: font_get_glyph_v_advance_func_t): void
export function fontFuncsSetGlyphVAdvancesFunc(ffuncs: font_funcs_t, func: font_get_glyph_v_advances_func_t): void
export function fontFuncsSetGlyphVKerningFunc(ffuncs: font_funcs_t, func: font_get_glyph_v_kerning_func_t): void
export function fontFuncsSetGlyphVOriginFunc(ffuncs: font_funcs_t, func: font_get_glyph_v_origin_func_t): void
export function fontFuncsSetGlyphVOriginsFunc(ffuncs: font_funcs_t, func: font_get_glyph_v_origins_func_t): void
export function fontFuncsSetNominalGlyphFunc(ffuncs: font_funcs_t, func: font_get_nominal_glyph_func_t): void
export function fontFuncsSetNominalGlyphsFunc(ffuncs: font_funcs_t, func: font_get_nominal_glyphs_func_t): void
export function fontFuncsSetPaintGlyphFunc(ffuncs: font_funcs_t, func: font_paint_glyph_func_t): void
export function fontFuncsSetPaintGlyphOrFailFunc(ffuncs: font_funcs_t, func: font_paint_glyph_or_fail_func_t): void
export function fontFuncsSetVariationGlyphFunc(ffuncs: font_funcs_t, func: font_get_variation_glyph_func_t): void
export function fontGetEmpty(): font_t
export function fontGetExtentsForDirection(font: font_t, direction: direction_t): /* extents */ font_extents_t
export function fontGetFace(font: font_t): face_t
export function fontGetGlyph(font: font_t, unicode: codepoint_t, variationSelector: codepoint_t): [ /* returnType */ bool_t, /* glyph */ codepoint_t ]
export function fontGetGlyphAdvanceForDirection(font: font_t, glyph: codepoint_t, direction: direction_t): [ /* x */ position_t, /* y */ position_t ]
export function fontGetGlyphAdvancesForDirection(font: font_t, direction: direction_t, count: number, firstGlyph: codepoint_t, glyphStride: number): [ /* firstAdvance */ position_t, /* advanceStride */ number ]
export function fontGetGlyphContourPoint(font: font_t, glyph: codepoint_t, pointIndex: number): [ /* returnType */ bool_t, /* x */ position_t, /* y */ position_t ]
export function fontGetGlyphContourPointForOrigin(font: font_t, glyph: codepoint_t, pointIndex: number, direction: direction_t): [ /* returnType */ bool_t, /* x */ position_t, /* y */ position_t ]
export function fontGetGlyphExtents(font: font_t, glyph: codepoint_t): [ /* returnType */ bool_t, /* extents */ glyph_extents_t ]
export function fontGetGlyphExtentsForOrigin(font: font_t, glyph: codepoint_t, direction: direction_t): [ /* returnType */ bool_t, /* extents */ glyph_extents_t ]
export function fontGetGlyphFromName(font: font_t, name: string[]): [ /* returnType */ bool_t, /* glyph */ codepoint_t ]
export function fontGetGlyphHAdvance(font: font_t, glyph: codepoint_t): position_t
export function fontGetGlyphHAdvances(font: font_t, count: number, firstGlyph: codepoint_t, glyphStride: number, advanceStride: number): /* firstAdvance */ position_t
export function fontGetGlyphHKerning(font: font_t, leftGlyph: codepoint_t, rightGlyph: codepoint_t): position_t
export function fontGetGlyphHOrigin(font: font_t, glyph: codepoint_t): [ /* returnType */ bool_t, /* x */ position_t, /* y */ position_t ]
export function fontGetGlyphHOrigins(font: font_t, count: number, firstGlyph: codepoint_t, glyphStride: number, xStride: number, yStride: number): [ /* returnType */ bool_t, /* firstX */ position_t, /* firstY */ position_t ]
export function fontGetGlyphKerningForDirection(font: font_t, firstGlyph: codepoint_t, secondGlyph: codepoint_t, direction: direction_t): [ /* x */ position_t, /* y */ position_t ]
export function fontGetGlyphName(font: font_t, glyph: codepoint_t): [ /* returnType */ bool_t, /* name */ string[] ]
export function fontGetGlyphOriginForDirection(font: font_t, glyph: codepoint_t, direction: direction_t): [ /* x */ position_t, /* y */ position_t ]
export function fontGetGlyphShape(font: font_t, glyph: codepoint_t, dfuncs: draw_funcs_t, drawData?: object | null): void
export function fontGetGlyphVAdvance(font: font_t, glyph: codepoint_t): position_t
export function fontGetGlyphVAdvances(font: font_t, count: number, firstGlyph: codepoint_t, glyphStride: number): [ /* firstAdvance */ position_t, /* advanceStride */ number ]
export function fontGetGlyphVKerning(font: font_t, topGlyph: codepoint_t, bottomGlyph: codepoint_t): position_t
export function fontGetGlyphVOrigin(font: font_t, glyph: codepoint_t): [ /* returnType */ bool_t, /* x */ position_t, /* y */ position_t ]
export function fontGetGlyphVOrigins(font: font_t, count: number, firstGlyph: codepoint_t, glyphStride: number, xStride: number, yStride: number): [ /* returnType */ bool_t, /* firstX */ position_t, /* firstY */ position_t ]
export function fontGetHExtents(font: font_t): [ /* returnType */ bool_t, /* extents */ font_extents_t ]
export function fontGetNominalGlyph(font: font_t, unicode: codepoint_t): [ /* returnType */ bool_t, /* glyph */ codepoint_t ]
export function fontGetNominalGlyphs(font: font_t, count: number, firstUnicode: codepoint_t, unicodeStride: number, glyphStride: number): [ /* returnType */ number, /* firstGlyph */ codepoint_t ]
export function fontGetParent(font: font_t): font_t
export function fontGetPpem(font: font_t): [ /* xPpem */ number, /* yPpem */ number ]
export function fontGetPtem(font: font_t): number
export function fontGetScale(font: font_t): [ /* xScale */ number, /* yScale */ number ]
export function fontGetSerial(font: font_t): number
export function fontGetSyntheticBold(font: font_t): [ /* xEmbolden */ number, /* yEmbolden */ number, /* inPlace */ bool_t ]
export function fontGetSyntheticSlant(font: font_t): number
export function fontGetVExtents(font: font_t): [ /* returnType */ bool_t, /* extents */ font_extents_t ]
export function fontGetVarCoordsDesign(font: font_t): [ /* returnType */ number, /* length */ number ]
export function fontGetVarCoordsNormalized(font: font_t): [ /* returnType */ number, /* length */ number ]
export function fontGetVarNamedInstance(font: font_t): number
export function fontGetVariationGlyph(font: font_t, unicode: codepoint_t, variationSelector: codepoint_t): [ /* returnType */ bool_t, /* glyph */ codepoint_t ]
export function fontGlyphFromString(font: font_t, s: any): [ /* returnType */ bool_t, /* glyph */ codepoint_t ]
export function fontGlyphToString(font: font_t, glyph: codepoint_t): /* s */ string[]
export function fontIsImmutable(font: font_t): bool_t
export function fontIsSynthetic(font: font_t): bool_t
export function fontListFuncs(): string[]
export function fontMakeImmutable(font: font_t): void
export function fontPaintGlyph(font: font_t, glyph: codepoint_t, pfuncs: paint_funcs_t, paintData: object | null, paletteIndex: number, foreground: color_t): void
export function fontPaintGlyphOrFail(font: font_t, glyph: codepoint_t, pfuncs: paint_funcs_t, paintData: object | null, paletteIndex: number, foreground: color_t): bool_t
export function fontSetFace(font: font_t, face: face_t): void
export function fontSetFuncsUsing(font: font_t, name: string): bool_t
export function fontSetParent(font: font_t, parent: font_t): void
export function fontSetPpem(font: font_t, xPpem: number, yPpem: number): void
export function fontSetPtem(font: font_t, ptem: number): void
export function fontSetScale(font: font_t, xScale: number, yScale: number): void
export function fontSetSyntheticBold(font: font_t, xEmbolden: number, yEmbolden: number, inPlace: bool_t): void
export function fontSetSyntheticSlant(font: font_t, slant: number): void
export function fontSetVarCoordsDesign(font: font_t, coords: number[]): void
export function fontSetVarCoordsNormalized(font: font_t, coords: number[]): void
export function fontSetVarNamedInstance(font: font_t, instanceIndex: number): void
export function fontSetVariation(font: font_t, tag: tag_t, value: number): void
export function fontSetVariations(font: font_t, variations: variation_t[]): void
export function fontSubtractGlyphOriginForDirection(font: font_t, glyph: codepoint_t, direction: direction_t, x: position_t, y: position_t): void
export function free(ptr?: object | null): void
export function ftFaceCreateCached(ftFace: freetype2.Face): face_t
export function ftFaceCreateFromBlobOrFail(blob: blob_t, index: number): face_t
export function ftFaceCreateFromFileOrFail(fileName: string, index: number): face_t
export function ftFaceCreateReferenced(ftFace: freetype2.Face): face_t
export function ftFontChanged(font: font_t): void
export function ftFontCreateReferenced(ftFace: freetype2.Face): font_t
export function ftFontGetLoadFlags(font: font_t): number
export function ftFontSetFuncs(font: font_t): void
export function ftFontSetLoadFlags(font: font_t, loadFlags: number): void
export function ftHbFontChanged(font: font_t): bool_t
export function glibBlobCreate(gbytes: any): blob_t
export function glibGetUnicodeFuncs(): unicode_funcs_t
export function glibScriptFromScript(script: script_t): GLib.UnicodeScript
export function glibScriptToScript(script: GLib.UnicodeScript): script_t
export function glyphInfoGetGlyphFlags(info: glyph_info_t): glyph_flags_t
export function languageFromString(str: any): language_t
export function languageGetDefault(): language_t
export function languageMatches(language: language_t, specific: language_t): bool_t
export function languageToString(language: language_t): string
export function malloc(size: number): object | null
export function mapAllocationSuccessful(map: map_t): bool_t
export function mapClear(map: map_t): void
export function mapCopy(map: map_t): map_t
export function mapCreate(): map_t
export function mapDel(map: map_t, key: codepoint_t): void
export function mapGet(map: map_t, key: codepoint_t): codepoint_t
export function mapGetEmpty(): map_t
export function mapGetPopulation(map: map_t): number
export function mapHas(map: map_t, key: codepoint_t): bool_t
export function mapHash(map: map_t): number
export function mapIsEmpty(map: map_t): bool_t
export function mapIsEqual(map: map_t, other: map_t): bool_t
export function mapKeys(map: map_t, keys: set_t): void
export function mapNext(map: map_t, idx: number): [ /* returnType */ bool_t, /* key */ codepoint_t, /* value */ codepoint_t ]
export function mapSet(map: map_t, key: codepoint_t, value: codepoint_t): void
export function mapUpdate(map: map_t, other: map_t): void
export function mapValues(map: map_t, values: set_t): void
export function otColorGlyphGetLayers(face: face_t, glyph: codepoint_t, startOffset: number): [ /* returnType */ number, /* layers */ ot_color_layer_t[] | null ]
export function otColorGlyphHasPaint(face: face_t, glyph: codepoint_t): bool_t
export function otColorGlyphReferencePng(font: font_t, glyph: codepoint_t): blob_t
export function otColorGlyphReferenceSvg(face: face_t, glyph: codepoint_t): blob_t
export function otColorHasLayers(face: face_t): bool_t
export function otColorHasPaint(face: face_t): bool_t
export function otColorHasPalettes(face: face_t): bool_t
export function otColorHasPng(face: face_t): bool_t
export function otColorHasSvg(face: face_t): bool_t
export function otColorPaletteColorGetNameId(face: face_t, colorIndex: number): ot_name_id_t
export function otColorPaletteGetColors(face: face_t, paletteIndex: number, startOffset: number): [ /* returnType */ number, /* colors */ color_t[] | null ]
export function otColorPaletteGetCount(face: face_t): number
export function otColorPaletteGetFlags(face: face_t, paletteIndex: number): ot_color_palette_flags_t
export function otColorPaletteGetNameId(face: face_t, paletteIndex: number): ot_name_id_t
export function otFontSetFuncs(font: font_t): void
export function otLayoutCollectFeatures(face: face_t, tableTag: tag_t, scripts?: tag_t[] | null, languages?: tag_t[] | null, features?: tag_t[] | null): /* featureIndexes */ set_t
export function otLayoutCollectFeaturesMap(face: face_t, tableTag: tag_t, scriptIndex: number, languageIndex: number): /* featureMap */ map_t
export function otLayoutCollectLookups(face: face_t, tableTag: tag_t, scripts?: tag_t[] | null, languages?: tag_t[] | null, features?: tag_t[] | null): /* lookupIndexes */ set_t
export function otLayoutFeatureGetCharacters(face: face_t, tableTag: tag_t, featureIndex: number, startOffset: number): [ /* returnType */ number, /* characters */ codepoint_t[] ]
export function otLayoutFeatureGetLookups(face: face_t, tableTag: tag_t, featureIndex: number, startOffset: number): [ /* returnType */ number, /* lookupIndexes */ number[] ]
export function otLayoutFeatureGetNameIds(face: face_t, tableTag: tag_t, featureIndex: number): [ /* returnType */ bool_t, /* labelId */ ot_name_id_t | null, /* tooltipId */ ot_name_id_t | null, /* sampleId */ ot_name_id_t | null, /* numNamedParameters */ number | null, /* firstParamId */ ot_name_id_t | null ]
export function otLayoutFeatureWithVariationsGetLookups(face: face_t, tableTag: tag_t, featureIndex: number, variationsIndex: number, startOffset: number): [ /* returnType */ number, /* lookupIndexes */ number[] ]
export function otLayoutGetAttachPoints(face: face_t, glyph: codepoint_t, startOffset: number): [ /* returnType */ number, /* pointArray */ number[] ]
export function otLayoutGetBaseline(font: font_t, baselineTag: ot_layout_baseline_tag_t, direction: direction_t, scriptTag: tag_t, languageTag: tag_t): [ /* returnType */ bool_t, /* coord */ position_t | null ]
export function otLayoutGetBaseline2(font: font_t, baselineTag: ot_layout_baseline_tag_t, direction: direction_t, script: script_t, language?: language_t | null): [ /* returnType */ bool_t, /* coord */ position_t | null ]
export function otLayoutGetBaselineWithFallback(font: font_t, baselineTag: ot_layout_baseline_tag_t, direction: direction_t, scriptTag: tag_t, languageTag: tag_t): /* coord */ position_t
export function otLayoutGetBaselineWithFallback2(font: font_t, baselineTag: ot_layout_baseline_tag_t, direction: direction_t, script: script_t, language?: language_t | null): /* coord */ position_t
export function otLayoutGetFontExtents(font: font_t, direction: direction_t, scriptTag: tag_t, languageTag: tag_t): [ /* returnType */ bool_t, /* extents */ font_extents_t | null ]
export function otLayoutGetFontExtents2(font: font_t, direction: direction_t, script: script_t, language?: language_t | null): [ /* returnType */ bool_t, /* extents */ font_extents_t | null ]
export function otLayoutGetGlyphClass(face: face_t, glyph: codepoint_t): ot_layout_glyph_class_t
export function otLayoutGetGlyphsInClass(face: face_t, klass: ot_layout_glyph_class_t): /* glyphs */ set_t
export function otLayoutGetHorizontalBaselineTagForScript(script: script_t): ot_layout_baseline_tag_t
export function otLayoutGetLigatureCarets(font: font_t, direction: direction_t, glyph: codepoint_t, startOffset: number): [ /* returnType */ number, /* caretArray */ position_t[] ]
export function otLayoutGetSizeParams(face: face_t): [ /* returnType */ bool_t, /* designSize */ number, /* subfamilyId */ number, /* subfamilyNameId */ ot_name_id_t, /* rangeStart */ number, /* rangeEnd */ number ]
export function otLayoutHasGlyphClasses(face: face_t): bool_t
export function otLayoutHasPositioning(face: face_t): bool_t
export function otLayoutHasSubstitution(face: face_t): bool_t
export function otLayoutLanguageFindFeature(face: face_t, tableTag: tag_t, scriptIndex: number, languageIndex: number, featureTag: tag_t): [ /* returnType */ bool_t, /* featureIndex */ number ]
export function otLayoutLanguageGetFeatureIndexes(face: face_t, tableTag: tag_t, scriptIndex: number, languageIndex: number, startOffset: number): [ /* returnType */ number, /* featureIndexes */ number[] ]
export function otLayoutLanguageGetFeatureTags(face: face_t, tableTag: tag_t, scriptIndex: number, languageIndex: number, startOffset: number): [ /* returnType */ number, /* featureTags */ tag_t[] ]
export function otLayoutLanguageGetRequiredFeature(face: face_t, tableTag: tag_t, scriptIndex: number, languageIndex: number): [ /* returnType */ bool_t, /* featureIndex */ number, /* featureTag */ tag_t ]
export function otLayoutLanguageGetRequiredFeatureIndex(face: face_t, tableTag: tag_t, scriptIndex: number, languageIndex: number): [ /* returnType */ bool_t, /* featureIndex */ number ]
export function otLayoutLookupCollectGlyphs(face: face_t, tableTag: tag_t, lookupIndex: number): [ /* glyphsBefore */ set_t | null, /* glyphsInput */ set_t | null, /* glyphsAfter */ set_t | null, /* glyphsOutput */ set_t | null ]
export function otLayoutLookupGetGlyphAlternates(face: face_t, lookupIndex: number, glyph: codepoint_t, startOffset: number): [ /* returnType */ number, /* alternateGlyphs */ codepoint_t[] ]
export function otLayoutLookupGetOpticalBound(font: font_t, lookupIndex: number, direction: direction_t, glyph: codepoint_t): position_t
export function otLayoutLookupSubstituteClosure(face: face_t, lookupIndex: number): /* glyphs */ set_t
export function otLayoutLookupWouldSubstitute(face: face_t, lookupIndex: number, glyphs: codepoint_t, glyphsLength: number, zeroContext: bool_t): bool_t
export function otLayoutLookupsSubstituteClosure(face: face_t, lookups: set_t): /* glyphs */ set_t
export function otLayoutScriptFindLanguage(face: face_t, tableTag: tag_t, scriptIndex: number, languageTag: tag_t, languageIndex: number): bool_t
export function otLayoutScriptGetLanguageTags(face: face_t, tableTag: tag_t, scriptIndex: number, startOffset: number): [ /* returnType */ number, /* languageTags */ tag_t[] ]
export function otLayoutScriptSelectLanguage(face: face_t, tableTag: tag_t, scriptIndex: number, languageCount: number, languageTags: tag_t): [ /* returnType */ bool_t, /* languageIndex */ number ]
export function otLayoutScriptSelectLanguage2(face: face_t, tableTag: tag_t, scriptIndex: number, languageCount: number, languageTags: tag_t): [ /* returnType */ bool_t, /* languageIndex */ number, /* chosenLanguage */ tag_t ]
export function otLayoutTableChooseScript(face: face_t, tableTag: tag_t, scriptTags: tag_t): [ /* returnType */ bool_t, /* scriptIndex */ number, /* chosenScript */ tag_t ]
export function otLayoutTableFindFeatureVariations(face: face_t, tableTag: tag_t, coords: number, numCoords: number): [ /* returnType */ bool_t, /* variationsIndex */ number ]
export function otLayoutTableFindScript(face: face_t, tableTag: tag_t, scriptTag: tag_t): [ /* returnType */ bool_t, /* scriptIndex */ number ]
export function otLayoutTableGetFeatureTags(face: face_t, tableTag: tag_t, startOffset: number): [ /* returnType */ number, /* featureTags */ tag_t[] ]
export function otLayoutTableGetLookupCount(face: face_t, tableTag: tag_t): number
export function otLayoutTableGetScriptTags(face: face_t, tableTag: tag_t, startOffset: number): [ /* returnType */ number, /* scriptTags */ tag_t[] ]
export function otLayoutTableSelectScript(face: face_t, tableTag: tag_t, scriptCount: number, scriptTags: tag_t): [ /* returnType */ bool_t, /* scriptIndex */ number | null, /* chosenScript */ tag_t | null ]
export function otMathGetConstant(font: font_t, constant: ot_math_constant_t): position_t
export function otMathGetGlyphAssembly(font: font_t, glyph: codepoint_t, direction: direction_t, startOffset: number): [ /* returnType */ number, /* parts */ ot_math_glyph_part_t[], /* italicsCorrection */ position_t ]
export function otMathGetGlyphItalicsCorrection(font: font_t, glyph: codepoint_t): position_t
export function otMathGetGlyphKerning(font: font_t, glyph: codepoint_t, kern: ot_math_kern_t, correctionHeight: position_t): position_t
export function otMathGetGlyphKernings(font: font_t, glyph: codepoint_t, kern: ot_math_kern_t, startOffset: number): [ /* returnType */ number, /* kernEntries */ ot_math_kern_entry_t[] ]
export function otMathGetGlyphTopAccentAttachment(font: font_t, glyph: codepoint_t): position_t
export function otMathGetGlyphVariants(font: font_t, glyph: codepoint_t, direction: direction_t, startOffset: number): [ /* returnType */ number, /* variants */ ot_math_glyph_variant_t[] ]
export function otMathGetMinConnectorOverlap(font: font_t, direction: direction_t): position_t
export function otMathHasData(face: face_t): bool_t
export function otMathIsGlyphExtendedShape(face: face_t, glyph: codepoint_t): bool_t
export function otMetaGetEntryTags(face: face_t, startOffset: number): [ /* returnType */ number, /* entries */ ot_meta_tag_t[] ]
export function otMetaReferenceEntry(face: face_t, metaTag: ot_meta_tag_t): blob_t
export function otMetricsGetPosition(font: font_t, metricsTag: ot_metrics_tag_t): [ /* returnType */ bool_t, /* position */ position_t | null ]
export function otMetricsGetPositionWithFallback(font: font_t, metricsTag: ot_metrics_tag_t): /* position */ position_t | null
export function otMetricsGetVariation(font: font_t, metricsTag: ot_metrics_tag_t): number
export function otMetricsGetXVariation(font: font_t, metricsTag: ot_metrics_tag_t): position_t
export function otMetricsGetYVariation(font: font_t, metricsTag: ot_metrics_tag_t): position_t
export function otNameGetUtf16(face: face_t, nameId: ot_name_id_t, language: language_t): [ /* returnType */ number, /* text */ number[] ]
export function otNameGetUtf32(face: face_t, nameId: ot_name_id_t, language: language_t): [ /* returnType */ number, /* text */ number[] ]
export function otNameGetUtf8(face: face_t, nameId: ot_name_id_t, language: language_t): [ /* returnType */ number, /* text */ string[] ]
export function otNameListNames(face: face_t): ot_name_entry_t[]
export function otShapeGlyphsClosure(font: font_t, buffer: buffer_t, features: feature_t[]): /* glyphs */ set_t
export function otShapePlanCollectLookups(shapePlan: shape_plan_t, tableTag: tag_t): /* lookupIndexes */ set_t
export function otShapePlanGetFeatureTags(shapePlan: shape_plan_t, startOffset: number): [ /* returnType */ number, /* tags */ tag_t[] ]
export function otTagFromLanguage(language: language_t): tag_t
export function otTagToLanguage(tag: tag_t): language_t | null
export function otTagToScript(tag: tag_t): script_t
export function otTagsFromScript(script: script_t): [ /* scriptTag1 */ tag_t, /* scriptTag2 */ tag_t ]
export function otTagsFromScriptAndLanguage(script: script_t, language: language_t | null, scriptCount: number, languageCount: number): [ /* scriptTags */ tag_t | null, /* languageTags */ tag_t | null ]
export function otTagsToScriptAndLanguage(scriptTag: tag_t, languageTag: tag_t): [ /* script */ script_t | null, /* language */ language_t | null ]
export function otVarFindAxis(face: face_t, axisTag: tag_t, axisIndex: number): [ /* returnType */ bool_t, /* axisInfo */ ot_var_axis_t ]
export function otVarFindAxisInfo(face: face_t, axisTag: tag_t): [ /* returnType */ bool_t, /* axisInfo */ ot_var_axis_info_t ]
export function otVarGetAxes(face: face_t, startOffset: number): [ /* returnType */ number, /* axesArray */ ot_var_axis_t[] ]
export function otVarGetAxisCount(face: face_t): number
export function otVarGetAxisInfos(face: face_t, startOffset: number): [ /* returnType */ number, /* axesArray */ ot_var_axis_info_t[] ]
export function otVarGetNamedInstanceCount(face: face_t): number
export function otVarHasData(face: face_t): bool_t
export function otVarNamedInstanceGetDesignCoords(face: face_t, instanceIndex: number): [ /* returnType */ number, /* coords */ number[] ]
export function otVarNamedInstanceGetPostscriptNameId(face: face_t, instanceIndex: number): ot_name_id_t
export function otVarNamedInstanceGetSubfamilyNameId(face: face_t, instanceIndex: number): ot_name_id_t
export function otVarNormalizeCoords(face: face_t, coordsLength: number, designCoords: number): /* normalizedCoords */ number
export function otVarNormalizeVariations(face: face_t, variations: variation_t, variationsLength: number): /* coords */ number[]
export function paintColor(funcs: paint_funcs_t, paintData: object | null, isForeground: bool_t, color: color_t): void
export function paintColorGlyph(funcs: paint_funcs_t, paintData: object | null, glyph: codepoint_t, font: font_t): bool_t
export function paintCustomPaletteColor(funcs: paint_funcs_t, paintData: object | null, colorIndex: number): [ /* returnType */ bool_t, /* color */ color_t ]
export function paintFuncsCreate(): paint_funcs_t
export function paintFuncsGetEmpty(): paint_funcs_t
export function paintFuncsIsImmutable(funcs: paint_funcs_t): bool_t
export function paintFuncsMakeImmutable(funcs: paint_funcs_t): void
export function paintFuncsSetColorFunc(funcs: paint_funcs_t, func: paint_color_func_t): void
export function paintFuncsSetColorGlyphFunc(funcs: paint_funcs_t, func: paint_color_glyph_func_t): void
export function paintFuncsSetCustomPaletteColorFunc(funcs: paint_funcs_t, func: paint_custom_palette_color_func_t): void
export function paintFuncsSetImageFunc(funcs: paint_funcs_t, func: paint_image_func_t): void
export function paintFuncsSetLinearGradientFunc(funcs: paint_funcs_t, func: paint_linear_gradient_func_t): void
export function paintFuncsSetPopClipFunc(funcs: paint_funcs_t, func: paint_pop_clip_func_t): void
export function paintFuncsSetPopGroupFunc(funcs: paint_funcs_t, func: paint_pop_group_func_t): void
export function paintFuncsSetPopTransformFunc(funcs: paint_funcs_t, func: paint_pop_transform_func_t): void
export function paintFuncsSetPushClipGlyphFunc(funcs: paint_funcs_t, func: paint_push_clip_glyph_func_t): void
export function paintFuncsSetPushClipRectangleFunc(funcs: paint_funcs_t, func: paint_push_clip_rectangle_func_t): void
export function paintFuncsSetPushGroupFunc(funcs: paint_funcs_t, func: paint_push_group_func_t): void
export function paintFuncsSetPushTransformFunc(funcs: paint_funcs_t, func: paint_push_transform_func_t): void
export function paintFuncsSetRadialGradientFunc(funcs: paint_funcs_t, func: paint_radial_gradient_func_t): void
export function paintFuncsSetSweepGradientFunc(funcs: paint_funcs_t, func: paint_sweep_gradient_func_t): void
export function paintImage(funcs: paint_funcs_t, paintData: object | null, image: blob_t, width: number, height: number, format: tag_t, slant: number, extents?: glyph_extents_t | null): void
export function paintLinearGradient(funcs: paint_funcs_t, paintData: object | null, colorLine: color_line_t, x0: number, y0: number, x1: number, y1: number, x2: number, y2: number): void
export function paintPopClip(funcs: paint_funcs_t, paintData?: object | null): void
export function paintPopGroup(funcs: paint_funcs_t, paintData: object | null, mode: paint_composite_mode_t): void
export function paintPopTransform(funcs: paint_funcs_t, paintData?: object | null): void
export function paintPushClipGlyph(funcs: paint_funcs_t, paintData: object | null, glyph: codepoint_t, font: font_t): void
export function paintPushClipRectangle(funcs: paint_funcs_t, paintData: object | null, xmin: number, ymin: number, xmax: number, ymax: number): void
export function paintPushFontTransform(funcs: paint_funcs_t, paintData: object | null, font: font_t): void
export function paintPushGroup(funcs: paint_funcs_t, paintData?: object | null): void
export function paintPushInverseFontTransform(funcs: paint_funcs_t, paintData: object | null, font: font_t): void
export function paintPushTransform(funcs: paint_funcs_t, paintData: object | null, xx: number, yx: number, xy: number, yy: number, dx: number, dy: number): void
export function paintRadialGradient(funcs: paint_funcs_t, paintData: object | null, colorLine: color_line_t, x0: number, y0: number, r0: number, x1: number, y1: number, r1: number): void
export function paintSweepGradient(funcs: paint_funcs_t, paintData: object | null, colorLine: color_line_t, x0: number, y0: number, startAngle: number, endAngle: number): void
export function realloc(ptr: object | null, size: number): object | null
export function scriptFromIso15924Tag(tag: tag_t): script_t
export function scriptFromString(str: any): script_t
export function scriptGetHorizontalDirection(script: script_t): direction_t
export function scriptToIso15924Tag(script: script_t): tag_t
export function segmentPropertiesEqual(a: segment_properties_t, b: segment_properties_t): bool_t
export function segmentPropertiesHash(p: segment_properties_t): number
export function segmentPropertiesOverlay(p: segment_properties_t, src: segment_properties_t): void
export function setAdd(set: set_t, codepoint: codepoint_t): void
export function setAddRange(set: set_t, first: codepoint_t, last: codepoint_t): void
export function setAddSortedArray(set: set_t, sortedCodepoints: codepoint_t[]): void
export function setAllocationSuccessful(set: set_t): bool_t
export function setClear(set: set_t): void
export function setCopy(set: set_t): set_t
export function setCreate(): set_t
export function setDel(set: set_t, codepoint: codepoint_t): void
export function setDelRange(set: set_t, first: codepoint_t, last: codepoint_t): void
export function setGetEmpty(): set_t
export function setGetMax(set: set_t): codepoint_t
export function setGetMin(set: set_t): codepoint_t
export function setGetPopulation(set: set_t): number
export function setHas(set: set_t, codepoint: codepoint_t): bool_t
export function setHash(set: set_t): number
export function setIntersect(set: set_t, other: set_t): void
export function setInvert(set: set_t): void
export function setIsEmpty(set: set_t): bool_t
export function setIsEqual(set: set_t, other: set_t): bool_t
export function setIsInverted(set: set_t): bool_t
export function setIsSubset(set: set_t, largerSet: set_t): bool_t
export function setNext(set: set_t, codepoint: codepoint_t): bool_t
export function setNextMany(set: set_t, codepoint: codepoint_t, out: codepoint_t[]): number
export function setNextRange(set: set_t, last: codepoint_t): [ /* returnType */ bool_t, /* first */ codepoint_t ]
export function setPrevious(set: set_t, codepoint: codepoint_t): bool_t
export function setPreviousRange(set: set_t, first: codepoint_t): [ /* returnType */ bool_t, /* last */ codepoint_t ]
export function setSet(set: set_t, other: set_t): void
export function setSubtract(set: set_t, other: set_t): void
export function setSymmetricDifference(set: set_t, other: set_t): void
export function setUnion(set: set_t, other: set_t): void
export function shape(font: font_t, buffer: buffer_t, features: feature_t[] | null): void
export function shapeFull(font: font_t, buffer: buffer_t, features: feature_t[] | null, shaperList?: string[] | null): bool_t
export function shapeListShapers(): string[]
export function shapePlanCreate(face: face_t, props: segment_properties_t, userFeatures: feature_t[], shaperList: string[]): shape_plan_t
export function shapePlanCreate2(face: face_t, props: segment_properties_t, userFeatures: feature_t[], coords: number[], shaperList: string[]): shape_plan_t
export function shapePlanCreateCached(face: face_t, props: segment_properties_t, userFeatures: feature_t[], shaperList: string[]): shape_plan_t
export function shapePlanCreateCached2(face: face_t, props: segment_properties_t, userFeatures: feature_t[], coords: number[], shaperList: string[]): shape_plan_t
export function shapePlanExecute(shapePlan: shape_plan_t, font: font_t, buffer: buffer_t, features: feature_t[]): bool_t
export function shapePlanGetEmpty(): shape_plan_t
export function shapePlanGetShaper(shapePlan: shape_plan_t): string
export function styleGetValue(font: font_t, styleTag: style_tag_t): number
export function tagFromString(str: any): tag_t
export function tagToString(tag: tag_t): /* buf */ any
export function unicodeCombiningClass(ufuncs: unicode_funcs_t, unicode: codepoint_t): unicode_combining_class_t
export function unicodeCompose(ufuncs: unicode_funcs_t, a: codepoint_t, b: codepoint_t): [ /* returnType */ bool_t, /* ab */ codepoint_t ]
export function unicodeDecompose(ufuncs: unicode_funcs_t, ab: codepoint_t): [ /* returnType */ bool_t, /* a */ codepoint_t, /* b */ codepoint_t ]
export function unicodeDecomposeCompatibility(ufuncs: unicode_funcs_t, u: codepoint_t): [ /* returnType */ number, /* decomposed */ codepoint_t ]
export function unicodeEastasianWidth(ufuncs: unicode_funcs_t, unicode: codepoint_t): number
export function unicodeFuncsCreate(parent?: unicode_funcs_t | null): unicode_funcs_t
export function unicodeFuncsGetDefault(): unicode_funcs_t
export function unicodeFuncsGetEmpty(): unicode_funcs_t
export function unicodeFuncsGetParent(ufuncs: unicode_funcs_t): unicode_funcs_t
export function unicodeFuncsIsImmutable(ufuncs: unicode_funcs_t): bool_t
export function unicodeFuncsMakeImmutable(ufuncs: unicode_funcs_t): void
export function unicodeFuncsSetCombiningClassFunc(ufuncs: unicode_funcs_t, func: unicode_combining_class_func_t): void
export function unicodeFuncsSetComposeFunc(ufuncs: unicode_funcs_t, func: unicode_compose_func_t): void
export function unicodeFuncsSetDecomposeCompatibilityFunc(ufuncs: unicode_funcs_t, func: unicode_decompose_compatibility_func_t): void
export function unicodeFuncsSetDecomposeFunc(ufuncs: unicode_funcs_t, func: unicode_decompose_func_t): void
export function unicodeFuncsSetEastasianWidthFunc(ufuncs: unicode_funcs_t, func: unicode_eastasian_width_func_t): void
export function unicodeFuncsSetGeneralCategoryFunc(ufuncs: unicode_funcs_t, func: unicode_general_category_func_t): void
export function unicodeFuncsSetMirroringFunc(ufuncs: unicode_funcs_t, func: unicode_mirroring_func_t): void
export function unicodeFuncsSetScriptFunc(ufuncs: unicode_funcs_t, func: unicode_script_func_t): void
export function unicodeGeneralCategory(ufuncs: unicode_funcs_t, unicode: codepoint_t): unicode_general_category_t
export function unicodeMirroring(ufuncs: unicode_funcs_t, unicode: codepoint_t): codepoint_t
export function unicodeScript(ufuncs: unicode_funcs_t, unicode: codepoint_t): script_t
export function variationFromString(str: any): [ /* returnType */ bool_t, /* variation */ variation_t ]
export function variationToString(variation: variation_t): /* buf */ string[]
export interface buffer_message_func_t {
    (buffer: buffer_t, font: font_t, message: string): bool_t
}
export interface color_line_get_color_stops_func_t {
    (colorLine: color_line_t, colorLineData: object | null, start: number): number
}
export interface color_line_get_extend_func_t {
    (colorLine: color_line_t, colorLineData?: object | null): paint_extend_t
}
export interface destroy_func_t {
    (): void
}
export interface draw_close_path_func_t {
    (dfuncs: draw_funcs_t, drawData: object | null, st: draw_state_t): void
}
export interface draw_cubic_to_func_t {
    (dfuncs: draw_funcs_t, drawData: object | null, st: draw_state_t, control1X: number, control1Y: number, control2X: number, control2Y: number, toX: number, toY: number): void
}
export interface draw_line_to_func_t {
    (dfuncs: draw_funcs_t, drawData: object | null, st: draw_state_t, toX: number, toY: number): void
}
export interface draw_move_to_func_t {
    (dfuncs: draw_funcs_t, drawData: object | null, st: draw_state_t, toX: number, toY: number): void
}
export interface draw_quadratic_to_func_t {
    (dfuncs: draw_funcs_t, drawData: object | null, st: draw_state_t, controlX: number, controlY: number, toX: number, toY: number): void
}
export interface font_draw_glyph_func_t {
    (font: font_t, fontData: object | null, glyph: codepoint_t, drawFuncs: draw_funcs_t, drawData?: object | null): void
}
export interface font_draw_glyph_or_fail_func_t {
    (font: font_t, fontData: object | null, glyph: codepoint_t, drawFuncs: draw_funcs_t, drawData?: object | null): bool_t
}
export interface font_get_font_extents_func_t {
    (font: font_t, fontData?: object | null): bool_t
}
export interface font_get_glyph_advance_func_t {
    (font: font_t, fontData: object | null, glyph: codepoint_t): position_t
}
export interface font_get_glyph_advances_func_t {
    (font: font_t, fontData: object | null, count: number, firstGlyph: codepoint_t, glyphStride: number, advanceStride: number): void
}
export interface font_get_glyph_contour_point_func_t {
    (font: font_t, fontData: object | null, glyph: codepoint_t, pointIndex: number): bool_t
}
export interface font_get_glyph_extents_func_t {
    (font: font_t, fontData: object | null, glyph: codepoint_t): bool_t
}
export interface font_get_glyph_from_name_func_t {
    (font: font_t, fontData: object | null, name: string[]): bool_t
}
export interface font_get_glyph_func_t {
    (font: font_t, fontData: object | null, unicode: codepoint_t, variationSelector: codepoint_t): bool_t
}
export interface font_get_glyph_kerning_func_t {
    (font: font_t, fontData: object | null, firstGlyph: codepoint_t, secondGlyph: codepoint_t): position_t
}
export interface font_get_glyph_name_func_t {
    (font: font_t, fontData: object | null, glyph: codepoint_t): bool_t
}
export interface font_get_glyph_origin_func_t {
    (font: font_t, fontData: object | null, glyph: codepoint_t): bool_t
}
export interface font_get_glyph_origins_func_t {
    (font: font_t, fontData: object | null, count: number, firstGlyph: codepoint_t, glyphStride: number, xStride: number, yStride: number): bool_t
}
export interface font_get_glyph_shape_func_t {
    (font: font_t, fontData: object | null, glyph: codepoint_t, drawFuncs: draw_funcs_t, drawData?: object | null): void
}
export interface font_get_nominal_glyph_func_t {
    (font: font_t, fontData: object | null, unicode: codepoint_t): bool_t
}
export interface font_get_nominal_glyphs_func_t {
    (font: font_t, fontData: object | null, count: number, firstUnicode: codepoint_t, unicodeStride: number, glyphStride: number): number
}
export interface font_get_variation_glyph_func_t {
    (font: font_t, fontData: object | null, unicode: codepoint_t, variationSelector: codepoint_t): bool_t
}
export interface font_paint_glyph_func_t {
    (font: font_t, fontData: object | null, glyph: codepoint_t, paintFuncs: paint_funcs_t, paintData: object | null, paletteIndex: number, foreground: color_t): bool_t
}
export interface font_paint_glyph_or_fail_func_t {
    (font: font_t, fontData: object | null, glyph: codepoint_t, paintFuncs: paint_funcs_t, paintData: object | null, paletteIndex: number, foreground: color_t): bool_t
}
export interface get_table_tags_func_t {
    (face: face_t, startOffset: number): number
}
export interface paint_color_func_t {
    (funcs: paint_funcs_t, paintData: object | null, isForeground: bool_t, color: color_t): void
}
export interface paint_color_glyph_func_t {
    (funcs: paint_funcs_t, paintData: object | null, glyph: codepoint_t, font: font_t): bool_t
}
export interface paint_custom_palette_color_func_t {
    (funcs: paint_funcs_t, paintData: object | null, colorIndex: number): bool_t
}
export interface paint_image_func_t {
    (funcs: paint_funcs_t, paintData: object | null, image: blob_t, width: number, height: number, format: tag_t, slant: number, extents?: glyph_extents_t | null): bool_t
}
export interface paint_linear_gradient_func_t {
    (funcs: paint_funcs_t, paintData: object | null, colorLine: color_line_t, x0: number, y0: number, x1: number, y1: number, x2: number, y2: number): void
}
export interface paint_pop_clip_func_t {
    (funcs: paint_funcs_t, paintData?: object | null): void
}
export interface paint_pop_group_func_t {
    (funcs: paint_funcs_t, paintData: object | null, mode: paint_composite_mode_t): void
}
export interface paint_pop_transform_func_t {
    (funcs: paint_funcs_t, paintData?: object | null): void
}
export interface paint_push_clip_glyph_func_t {
    (funcs: paint_funcs_t, paintData: object | null, glyph: codepoint_t, font: font_t): void
}
export interface paint_push_clip_rectangle_func_t {
    (funcs: paint_funcs_t, paintData: object | null, xmin: number, ymin: number, xmax: number, ymax: number): void
}
export interface paint_push_group_func_t {
    (funcs: paint_funcs_t, paintData?: object | null): void
}
export interface paint_push_transform_func_t {
    (funcs: paint_funcs_t, paintData: object | null, xx: number, yx: number, xy: number, yy: number, dx: number, dy: number): void
}
export interface paint_radial_gradient_func_t {
    (funcs: paint_funcs_t, paintData: object | null, colorLine: color_line_t, x0: number, y0: number, r0: number, x1: number, y1: number, r1: number): void
}
export interface paint_sweep_gradient_func_t {
    (funcs: paint_funcs_t, paintData: object | null, colorLine: color_line_t, x0: number, y0: number, startAngle: number, endAngle: number): void
}
export interface reference_table_func_t {
    (face: face_t, tag: tag_t): blob_t
}
export interface unicode_combining_class_func_t {
    (ufuncs: unicode_funcs_t, unicode: codepoint_t): unicode_combining_class_t
}
export interface unicode_compose_func_t {
    (ufuncs: unicode_funcs_t, a: codepoint_t, b: codepoint_t): bool_t
}
export interface unicode_decompose_compatibility_func_t {
    (ufuncs: unicode_funcs_t, u: codepoint_t, decomposed: codepoint_t): number
}
export interface unicode_decompose_func_t {
    (ufuncs: unicode_funcs_t, ab: codepoint_t): bool_t
}
export interface unicode_eastasian_width_func_t {
    (ufuncs: unicode_funcs_t, unicode: codepoint_t): number
}
export interface unicode_general_category_func_t {
    (ufuncs: unicode_funcs_t, unicode: codepoint_t): unicode_general_category_t
}
export interface unicode_mirroring_func_t {
    (ufuncs: unicode_funcs_t, unicode: codepoint_t): codepoint_t
}
export interface unicode_script_func_t {
    (ufuncs: unicode_funcs_t, unicode: codepoint_t): script_t
}
export class aat_layout_feature_selector_info_t {
    /* Fields of HarfBuzz.aat_layout_feature_selector_info_t */
    nameId: ot_name_id_t
    enable: aat_layout_feature_selector_t
    disable: aat_layout_feature_selector_t
    static name: string
}
export class blob_t {
    static name: string
}
export class buffer_t {
    static name: string
}
export class color_line_t {
    /* Fields of HarfBuzz.color_line_t */
    data: object
    getColorStops: color_line_get_color_stops_func_t
    getColorStopsUserData: object
    getExtend: color_line_get_extend_func_t
    getExtendUserData: object
    reserved0: object
    reserved1: object
    reserved2: object
    reserved3: object
    reserved5: object
    reserved6: object
    reserved7: object
    reserved8: object
    static name: string
}
export class color_stop_t {
    /* Fields of HarfBuzz.color_stop_t */
    offset: number
    isForeground: bool_t
    color: color_t
    static name: string
}
export class draw_funcs_t {
    static name: string
}
export class draw_state_t {
    /* Fields of HarfBuzz.draw_state_t */
    pathOpen: bool_t
    pathStartX: number
    pathStartY: number
    currentX: number
    currentY: number
    static name: string
}
export class face_t {
    static name: string
}
export class feature_t {
    /* Fields of HarfBuzz.feature_t */
    tag: tag_t
    value: number
    start: number
    end: number
    /* Methods of HarfBuzz.feature_t */
    string(): /* buf */ string[]
    static name: string
}
export class font_extents_t {
    /* Fields of HarfBuzz.font_extents_t */
    ascender: position_t
    descender: position_t
    lineGap: position_t
    static name: string
}
export class font_funcs_t {
    static name: string
}
export class font_t {
    static name: string
}
export class glyph_extents_t {
    /* Fields of HarfBuzz.glyph_extents_t */
    xBearing: position_t
    yBearing: position_t
    width: position_t
    height: position_t
    static name: string
}
export class glyph_info_t {
    /* Fields of HarfBuzz.glyph_info_t */
    codepoint: codepoint_t
    cluster: number
    static name: string
}
export class glyph_position_t {
    /* Fields of HarfBuzz.glyph_position_t */
    xAdvance: position_t
    yAdvance: position_t
    xOffset: position_t
    yOffset: position_t
    static name: string
}
export class language_t {
    /* Methods of HarfBuzz.language_t */
    string(): string
    static name: string
}
export class map_t {
    static name: string
}
export class ot_color_layer_t {
    /* Fields of HarfBuzz.ot_color_layer_t */
    glyph: codepoint_t
    colorIndex: number
    static name: string
}
export class ot_math_glyph_part_t {
    /* Fields of HarfBuzz.ot_math_glyph_part_t */
    glyph: codepoint_t
    startConnectorLength: position_t
    endConnectorLength: position_t
    fullAdvance: position_t
    flags: ot_math_glyph_part_flags_t
    static name: string
}
export class ot_math_glyph_variant_t {
    /* Fields of HarfBuzz.ot_math_glyph_variant_t */
    glyph: codepoint_t
    advance: position_t
    static name: string
}
export class ot_math_kern_entry_t {
    /* Fields of HarfBuzz.ot_math_kern_entry_t */
    maxCorrectionHeight: position_t
    kernValue: position_t
    static name: string
}
export class ot_name_entry_t {
    /* Fields of HarfBuzz.ot_name_entry_t */
    nameId: ot_name_id_t
    language: language_t
    static name: string
}
export class ot_var_axis_info_t {
    /* Fields of HarfBuzz.ot_var_axis_info_t */
    axisIndex: number
    tag: tag_t
    nameId: ot_name_id_t
    flags: ot_var_axis_flags_t
    minValue: number
    defaultValue: number
    maxValue: number
    static name: string
}
export class ot_var_axis_t {
    /* Fields of HarfBuzz.ot_var_axis_t */
    tag: tag_t
    nameId: ot_name_id_t
    minValue: number
    defaultValue: number
    maxValue: number
    static name: string
}
export class paint_funcs_t {
    static name: string
}
export class segment_properties_t {
    /* Fields of HarfBuzz.segment_properties_t */
    direction: direction_t
    script: script_t
    language: language_t
    static name: string
}
export class set_t {
    static name: string
}
export class shape_plan_t {
    static name: string
}
export class unicode_funcs_t {
    static name: string
}
export class user_data_key_t {
    /* Fields of HarfBuzz.user_data_key_t */
    static name: string
}
export class variation_t {
    /* Fields of HarfBuzz.variation_t */
    tag: tag_t
    value: number
    /* Methods of HarfBuzz.variation_t */
    string(): /* buf */ string[]
    static name: string
}
export class var_int_t {
    /* Fields of HarfBuzz.var_int_t */
    u32: number
    i32: number
    u16: number[]
    i16: number[]
    u8: any
    i8: any
    static name: string
}
export class var_num_t {
    /* Fields of HarfBuzz.var_num_t */
    f: number
    u32: number
    i32: number
    u16: number[]
    i16: number[]
    u8: any
    i8: any
    static name: string
}
type bool_t = number
type codepoint_t = number
type color_t = number
type font_get_font_h_extents_func_t = font_get_font_extents_func_t
type font_get_font_v_extents_func_t = font_get_font_extents_func_t
type font_get_glyph_h_advance_func_t = font_get_glyph_advance_func_t
type font_get_glyph_h_advances_func_t = font_get_glyph_advances_func_t
type font_get_glyph_h_kerning_func_t = font_get_glyph_kerning_func_t
type font_get_glyph_h_origin_func_t = font_get_glyph_origin_func_t
type font_get_glyph_h_origins_func_t = font_get_glyph_origins_func_t
type font_get_glyph_v_advance_func_t = font_get_glyph_advance_func_t
type font_get_glyph_v_advances_func_t = font_get_glyph_advances_func_t
type font_get_glyph_v_kerning_func_t = font_get_glyph_kerning_func_t
type font_get_glyph_v_origin_func_t = font_get_glyph_origin_func_t
type font_get_glyph_v_origins_func_t = font_get_glyph_origins_func_t
type mask_t = number
type ot_name_id_t = number
type position_t = number
type tag_t = number
}